/*
 *
 * SUMP Protocol Implementation for Arduino boards.
 *
 * Copyright (c) 2011,2012,2013,2014,2015 Andrew Gillham
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY ANDREW GILLHAM ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL ANDREW GILLHAM BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 */


/*
 * This function samples data using an unrolled loop for increased speed.
 * It also has rudimentary trigger support where it will just sit in
 * a busy loop waiting for the trigger conditions to occur.
 *
 * This loop is not clocked to the sample rate in any way, it just
 * reads the port as fast as possible waiting for a trigger match.
 * Multiple channels can have triggers enabled and can have different
 * trigger values.  All conditions must match to trigger.
 *
 * After the trigger fires (if it is enabled) the pins are sampled
 * at the appropriate rate.
 * 
 * We can only use 2048 datapoints at 5Mhz because of STM32s flash size.
 *
 */

void captureInline5mhz() {
  unsigned int i;

  /*
   * basic trigger, wait until all trigger conditions are met on port.
   * this needs further testing, but basic tests work as expected.
   */
  if (trigger) {
    while ((trigger_values ^ CHANPIN) & trigger);
  }

  /*
   * disable interrupts during capture to maintain precision.
   * we cannot afford any timing interference so we absolutely
   * cannot have any interrupts firing.
   */
  //cli();

  /*
   * toggle pin a few times to activate trigger for debugging.
   * this is used during development to measure the sample intervals.
   * it is best to just leave the toggling in place so we don't alter
   * any timing unexpectedly.
   */
  DEBUG_ENABLE;
  DEBUG_ON;
  delayMicroseconds(1);
  DEBUG_OFF;
  delayMicroseconds(1);
  DEBUG_ON;
  delayMicroseconds(1);
  DEBUG_OFF;
  delayMicroseconds(1);

  DEBUG_ON; /* debug timing measurement */

  /*
   * Unroll loop to maximize capture speed.
   * Pad with 5 cycles to make this run at 2MHz.
   * Using the RJMP instructions (instead of NOP) reduces flash usage by 4096 bytes.
   *
   */

#undef INLINE_NOP
#define INLINE_NOP    __asm__("nop\n\t");

  logicdata[0] = CHANPIN;
  INLINE_NOP;
  logicdata[1] = CHANPIN;
  INLINE_NOP;
  logicdata[2] = CHANPIN;
  INLINE_NOP;
  logicdata[3] = CHANPIN;
  INLINE_NOP;
  logicdata[4] = CHANPIN;
  INLINE_NOP;
  logicdata[5] = CHANPIN;
  INLINE_NOP;
  logicdata[6] = CHANPIN;
  INLINE_NOP;
  logicdata[7] = CHANPIN;
  INLINE_NOP;
  logicdata[8] = CHANPIN;
  INLINE_NOP;
  logicdata[9] = CHANPIN;
  INLINE_NOP;
  logicdata[10] = CHANPIN;
  INLINE_NOP;
  logicdata[11] = CHANPIN;
  INLINE_NOP;
  logicdata[12] = CHANPIN;
  INLINE_NOP;
  logicdata[13] = CHANPIN;
  INLINE_NOP;
  logicdata[14] = CHANPIN;
  INLINE_NOP;
  logicdata[15] = CHANPIN;
  INLINE_NOP;
  logicdata[16] = CHANPIN;
  INLINE_NOP;
  logicdata[17] = CHANPIN;
  INLINE_NOP;
  logicdata[18] = CHANPIN;
  INLINE_NOP;
  logicdata[19] = CHANPIN;
  INLINE_NOP;
  logicdata[20] = CHANPIN;
  INLINE_NOP;
  logicdata[21] = CHANPIN;
  INLINE_NOP;
  logicdata[22] = CHANPIN;
  INLINE_NOP;
  logicdata[23] = CHANPIN;
  INLINE_NOP;
  logicdata[24] = CHANPIN;
  INLINE_NOP;
  logicdata[25] = CHANPIN;
  INLINE_NOP;
  logicdata[26] = CHANPIN;
  INLINE_NOP;
  logicdata[27] = CHANPIN;
  INLINE_NOP;
  logicdata[28] = CHANPIN;
  INLINE_NOP;
  logicdata[29] = CHANPIN;
  INLINE_NOP;
  logicdata[30] = CHANPIN;
  INLINE_NOP;
  logicdata[31] = CHANPIN;
  INLINE_NOP;
  logicdata[32] = CHANPIN;
  INLINE_NOP;
  logicdata[33] = CHANPIN;
  INLINE_NOP;
  logicdata[34] = CHANPIN;
  INLINE_NOP;
  logicdata[35] = CHANPIN;
  INLINE_NOP;
  logicdata[36] = CHANPIN;
  INLINE_NOP;
  logicdata[37] = CHANPIN;
  INLINE_NOP;
  logicdata[38] = CHANPIN;
  INLINE_NOP;
  logicdata[39] = CHANPIN;
  INLINE_NOP;
  logicdata[40] = CHANPIN;
  INLINE_NOP;
  logicdata[41] = CHANPIN;
  INLINE_NOP;
  logicdata[42] = CHANPIN;
  INLINE_NOP;
  logicdata[43] = CHANPIN;
  INLINE_NOP;
  logicdata[44] = CHANPIN;
  INLINE_NOP;
  logicdata[45] = CHANPIN;
  INLINE_NOP;
  logicdata[46] = CHANPIN;
  INLINE_NOP;
  logicdata[47] = CHANPIN;
  INLINE_NOP;
  logicdata[48] = CHANPIN;
  INLINE_NOP;
  logicdata[49] = CHANPIN;
  INLINE_NOP;
  logicdata[50] = CHANPIN;
  INLINE_NOP;
  logicdata[51] = CHANPIN;
  INLINE_NOP;
  logicdata[52] = CHANPIN;
  INLINE_NOP;
  logicdata[53] = CHANPIN;
  INLINE_NOP;
  logicdata[54] = CHANPIN;
  INLINE_NOP;
  logicdata[55] = CHANPIN;
  INLINE_NOP;
  logicdata[56] = CHANPIN;
  INLINE_NOP;
  logicdata[57] = CHANPIN;
  INLINE_NOP;
  logicdata[58] = CHANPIN;
  INLINE_NOP;
  logicdata[59] = CHANPIN;
  INLINE_NOP;
  logicdata[60] = CHANPIN;
  INLINE_NOP;
  logicdata[61] = CHANPIN;
  INLINE_NOP;
  logicdata[62] = CHANPIN;
  INLINE_NOP;
  logicdata[63] = CHANPIN;
  INLINE_NOP;
  logicdata[64] = CHANPIN;
  INLINE_NOP;
  logicdata[65] = CHANPIN;
  INLINE_NOP;
  logicdata[66] = CHANPIN;
  INLINE_NOP;
  logicdata[67] = CHANPIN;
  INLINE_NOP;
  logicdata[68] = CHANPIN;
  INLINE_NOP;
  logicdata[69] = CHANPIN;
  INLINE_NOP;
  logicdata[70] = CHANPIN;
  INLINE_NOP;
  logicdata[71] = CHANPIN;
  INLINE_NOP;
  logicdata[72] = CHANPIN;
  INLINE_NOP;
  logicdata[73] = CHANPIN;
  INLINE_NOP;
  logicdata[74] = CHANPIN;
  INLINE_NOP;
  logicdata[75] = CHANPIN;
  INLINE_NOP;
  logicdata[76] = CHANPIN;
  INLINE_NOP;
  logicdata[77] = CHANPIN;
  INLINE_NOP;
  logicdata[78] = CHANPIN;
  INLINE_NOP;
  logicdata[79] = CHANPIN;
  INLINE_NOP;
  logicdata[80] = CHANPIN;
  INLINE_NOP;
  logicdata[81] = CHANPIN;
  INLINE_NOP;
  logicdata[82] = CHANPIN;
  INLINE_NOP;
  logicdata[83] = CHANPIN;
  INLINE_NOP;
  logicdata[84] = CHANPIN;
  INLINE_NOP;
  logicdata[85] = CHANPIN;
  INLINE_NOP;
  logicdata[86] = CHANPIN;
  INLINE_NOP;
  logicdata[87] = CHANPIN;
  INLINE_NOP;
  logicdata[88] = CHANPIN;
  INLINE_NOP;
  logicdata[89] = CHANPIN;
  INLINE_NOP;
  logicdata[90] = CHANPIN;
  INLINE_NOP;
  logicdata[91] = CHANPIN;
  INLINE_NOP;
  logicdata[92] = CHANPIN;
  INLINE_NOP;
  logicdata[93] = CHANPIN;
  INLINE_NOP;
  logicdata[94] = CHANPIN;
  INLINE_NOP;
  logicdata[95] = CHANPIN;
  INLINE_NOP;
  logicdata[96] = CHANPIN;
  INLINE_NOP;
  logicdata[97] = CHANPIN;
  INLINE_NOP;
  logicdata[98] = CHANPIN;
  INLINE_NOP;
  logicdata[99] = CHANPIN;
  INLINE_NOP;
  logicdata[100] = CHANPIN;
  INLINE_NOP;
  logicdata[101] = CHANPIN;
  INLINE_NOP;
  logicdata[102] = CHANPIN;
  INLINE_NOP;
  logicdata[103] = CHANPIN;
  INLINE_NOP;
  logicdata[104] = CHANPIN;
  INLINE_NOP;
  logicdata[105] = CHANPIN;
  INLINE_NOP;
  logicdata[106] = CHANPIN;
  INLINE_NOP;
  logicdata[107] = CHANPIN;
  INLINE_NOP;
  logicdata[108] = CHANPIN;
  INLINE_NOP;
  logicdata[109] = CHANPIN;
  INLINE_NOP;
  logicdata[110] = CHANPIN;
  INLINE_NOP;
  logicdata[111] = CHANPIN;
  INLINE_NOP;
  logicdata[112] = CHANPIN;
  INLINE_NOP;
  logicdata[113] = CHANPIN;
  INLINE_NOP;
  logicdata[114] = CHANPIN;
  INLINE_NOP;
  logicdata[115] = CHANPIN;
  INLINE_NOP;
  logicdata[116] = CHANPIN;
  INLINE_NOP;
  logicdata[117] = CHANPIN;
  INLINE_NOP;
  logicdata[118] = CHANPIN;
  INLINE_NOP;
  logicdata[119] = CHANPIN;
  INLINE_NOP;
  logicdata[120] = CHANPIN;
  INLINE_NOP;
  logicdata[121] = CHANPIN;
  INLINE_NOP;
  logicdata[122] = CHANPIN;
  INLINE_NOP;
  logicdata[123] = CHANPIN;
  INLINE_NOP;
  logicdata[124] = CHANPIN;
  INLINE_NOP;
  logicdata[125] = CHANPIN;
  INLINE_NOP;
  logicdata[126] = CHANPIN;
  INLINE_NOP;
  logicdata[127] = CHANPIN;
  INLINE_NOP;
  logicdata[128] = CHANPIN;
  INLINE_NOP;
  logicdata[129] = CHANPIN;
  INLINE_NOP;
  logicdata[130] = CHANPIN;
  INLINE_NOP;
  logicdata[131] = CHANPIN;
  INLINE_NOP;
  logicdata[132] = CHANPIN;
  INLINE_NOP;
  logicdata[133] = CHANPIN;
  INLINE_NOP;
  logicdata[134] = CHANPIN;
  INLINE_NOP;
  logicdata[135] = CHANPIN;
  INLINE_NOP;
  logicdata[136] = CHANPIN;
  INLINE_NOP;
  logicdata[137] = CHANPIN;
  INLINE_NOP;
  logicdata[138] = CHANPIN;
  INLINE_NOP;
  logicdata[139] = CHANPIN;
  INLINE_NOP;
  logicdata[140] = CHANPIN;
  INLINE_NOP;
  logicdata[141] = CHANPIN;
  INLINE_NOP;
  logicdata[142] = CHANPIN;
  INLINE_NOP;
  logicdata[143] = CHANPIN;
  INLINE_NOP;
  logicdata[144] = CHANPIN;
  INLINE_NOP;
  logicdata[145] = CHANPIN;
  INLINE_NOP;
  logicdata[146] = CHANPIN;
  INLINE_NOP;
  logicdata[147] = CHANPIN;
  INLINE_NOP;
  logicdata[148] = CHANPIN;
  INLINE_NOP;
  logicdata[149] = CHANPIN;
  INLINE_NOP;
  logicdata[150] = CHANPIN;
  INLINE_NOP;
  logicdata[151] = CHANPIN;
  INLINE_NOP;
  logicdata[152] = CHANPIN;
  INLINE_NOP;
  logicdata[153] = CHANPIN;
  INLINE_NOP;
  logicdata[154] = CHANPIN;
  INLINE_NOP;
  logicdata[155] = CHANPIN;
  INLINE_NOP;
  logicdata[156] = CHANPIN;
  INLINE_NOP;
  logicdata[157] = CHANPIN;
  INLINE_NOP;
  logicdata[158] = CHANPIN;
  INLINE_NOP;
  logicdata[159] = CHANPIN;
  INLINE_NOP;
  logicdata[160] = CHANPIN;
  INLINE_NOP;
  logicdata[161] = CHANPIN;
  INLINE_NOP;
  logicdata[162] = CHANPIN;
  INLINE_NOP;
  logicdata[163] = CHANPIN;
  INLINE_NOP;
  logicdata[164] = CHANPIN;
  INLINE_NOP;
  logicdata[165] = CHANPIN;
  INLINE_NOP;
  logicdata[166] = CHANPIN;
  INLINE_NOP;
  logicdata[167] = CHANPIN;
  INLINE_NOP;
  logicdata[168] = CHANPIN;
  INLINE_NOP;
  logicdata[169] = CHANPIN;
  INLINE_NOP;
  logicdata[170] = CHANPIN;
  INLINE_NOP;
  logicdata[171] = CHANPIN;
  INLINE_NOP;
  logicdata[172] = CHANPIN;
  INLINE_NOP;
  logicdata[173] = CHANPIN;
  INLINE_NOP;
  logicdata[174] = CHANPIN;
  INLINE_NOP;
  logicdata[175] = CHANPIN;
  INLINE_NOP;
  logicdata[176] = CHANPIN;
  INLINE_NOP;
  logicdata[177] = CHANPIN;
  INLINE_NOP;
  logicdata[178] = CHANPIN;
  INLINE_NOP;
  logicdata[179] = CHANPIN;
  INLINE_NOP;
  logicdata[180] = CHANPIN;
  INLINE_NOP;
  logicdata[181] = CHANPIN;
  INLINE_NOP;
  logicdata[182] = CHANPIN;
  INLINE_NOP;
  logicdata[183] = CHANPIN;
  INLINE_NOP;
  logicdata[184] = CHANPIN;
  INLINE_NOP;
  logicdata[185] = CHANPIN;
  INLINE_NOP;
  logicdata[186] = CHANPIN;
  INLINE_NOP;
  logicdata[187] = CHANPIN;
  INLINE_NOP;
  logicdata[188] = CHANPIN;
  INLINE_NOP;
  logicdata[189] = CHANPIN;
  INLINE_NOP;
  logicdata[190] = CHANPIN;
  INLINE_NOP;
  logicdata[191] = CHANPIN;
  INLINE_NOP;
  logicdata[192] = CHANPIN;
  INLINE_NOP;
  logicdata[193] = CHANPIN;
  INLINE_NOP;
  logicdata[194] = CHANPIN;
  INLINE_NOP;
  logicdata[195] = CHANPIN;
  INLINE_NOP;
  logicdata[196] = CHANPIN;
  INLINE_NOP;
  logicdata[197] = CHANPIN;
  INLINE_NOP;
  logicdata[198] = CHANPIN;
  INLINE_NOP;
  logicdata[199] = CHANPIN;
  INLINE_NOP;
  logicdata[200] = CHANPIN;
  INLINE_NOP;
  logicdata[201] = CHANPIN;
  INLINE_NOP;
  logicdata[202] = CHANPIN;
  INLINE_NOP;
  logicdata[203] = CHANPIN;
  INLINE_NOP;
  logicdata[204] = CHANPIN;
  INLINE_NOP;
  logicdata[205] = CHANPIN;
  INLINE_NOP;
  logicdata[206] = CHANPIN;
  INLINE_NOP;
  logicdata[207] = CHANPIN;
  INLINE_NOP;
  logicdata[208] = CHANPIN;
  INLINE_NOP;
  logicdata[209] = CHANPIN;
  INLINE_NOP;
  logicdata[210] = CHANPIN;
  INLINE_NOP;
  logicdata[211] = CHANPIN;
  INLINE_NOP;
  logicdata[212] = CHANPIN;
  INLINE_NOP;
  logicdata[213] = CHANPIN;
  INLINE_NOP;
  logicdata[214] = CHANPIN;
  INLINE_NOP;
  logicdata[215] = CHANPIN;
  INLINE_NOP;
  logicdata[216] = CHANPIN;
  INLINE_NOP;
  logicdata[217] = CHANPIN;
  INLINE_NOP;
  logicdata[218] = CHANPIN;
  INLINE_NOP;
  logicdata[219] = CHANPIN;
  INLINE_NOP;
  logicdata[220] = CHANPIN;
  INLINE_NOP;
  logicdata[221] = CHANPIN;
  INLINE_NOP;
  logicdata[222] = CHANPIN;
  INLINE_NOP;
  logicdata[223] = CHANPIN;
  INLINE_NOP;
  logicdata[224] = CHANPIN;
  INLINE_NOP;
  logicdata[225] = CHANPIN;
  INLINE_NOP;
  logicdata[226] = CHANPIN;
  INLINE_NOP;
  logicdata[227] = CHANPIN;
  INLINE_NOP;
  logicdata[228] = CHANPIN;
  INLINE_NOP;
  logicdata[229] = CHANPIN;
  INLINE_NOP;
  logicdata[230] = CHANPIN;
  INLINE_NOP;
  logicdata[231] = CHANPIN;
  INLINE_NOP;
  logicdata[232] = CHANPIN;
  INLINE_NOP;
  logicdata[233] = CHANPIN;
  INLINE_NOP;
  logicdata[234] = CHANPIN;
  INLINE_NOP;
  logicdata[235] = CHANPIN;
  INLINE_NOP;
  logicdata[236] = CHANPIN;
  INLINE_NOP;
  logicdata[237] = CHANPIN;
  INLINE_NOP;
  logicdata[238] = CHANPIN;
  INLINE_NOP;
  logicdata[239] = CHANPIN;
  INLINE_NOP;
  logicdata[240] = CHANPIN;
  INLINE_NOP;
  logicdata[241] = CHANPIN;
  INLINE_NOP;
  logicdata[242] = CHANPIN;
  INLINE_NOP;
  logicdata[243] = CHANPIN;
  INLINE_NOP;
  logicdata[244] = CHANPIN;
  INLINE_NOP;
  logicdata[245] = CHANPIN;
  INLINE_NOP;
  logicdata[246] = CHANPIN;
  INLINE_NOP;
  logicdata[247] = CHANPIN;
  INLINE_NOP;
  logicdata[248] = CHANPIN;
  INLINE_NOP;
  logicdata[249] = CHANPIN;
  INLINE_NOP;
  logicdata[250] = CHANPIN;
  INLINE_NOP;
  logicdata[251] = CHANPIN;
  INLINE_NOP;
  logicdata[252] = CHANPIN;
  INLINE_NOP;
  logicdata[253] = CHANPIN;
  INLINE_NOP;
  logicdata[254] = CHANPIN;
  INLINE_NOP;
  logicdata[255] = CHANPIN;
  INLINE_NOP;
  logicdata[256] = CHANPIN;
  INLINE_NOP;
  logicdata[257] = CHANPIN;
  INLINE_NOP;
  logicdata[258] = CHANPIN;
  INLINE_NOP;
  logicdata[259] = CHANPIN;
  INLINE_NOP;
  logicdata[260] = CHANPIN;
  INLINE_NOP;
  logicdata[261] = CHANPIN;
  INLINE_NOP;
  logicdata[262] = CHANPIN;
  INLINE_NOP;
  logicdata[263] = CHANPIN;
  INLINE_NOP;
  logicdata[264] = CHANPIN;
  INLINE_NOP;
  logicdata[265] = CHANPIN;
  INLINE_NOP;
  logicdata[266] = CHANPIN;
  INLINE_NOP;
  logicdata[267] = CHANPIN;
  INLINE_NOP;
  logicdata[268] = CHANPIN;
  INLINE_NOP;
  logicdata[269] = CHANPIN;
  INLINE_NOP;
  logicdata[270] = CHANPIN;
  INLINE_NOP;
  logicdata[271] = CHANPIN;
  INLINE_NOP;
  logicdata[272] = CHANPIN;
  INLINE_NOP;
  logicdata[273] = CHANPIN;
  INLINE_NOP;
  logicdata[274] = CHANPIN;
  INLINE_NOP;
  logicdata[275] = CHANPIN;
  INLINE_NOP;
  logicdata[276] = CHANPIN;
  INLINE_NOP;
  logicdata[277] = CHANPIN;
  INLINE_NOP;
  logicdata[278] = CHANPIN;
  INLINE_NOP;
  logicdata[279] = CHANPIN;
  INLINE_NOP;
  logicdata[280] = CHANPIN;
  INLINE_NOP;
  logicdata[281] = CHANPIN;
  INLINE_NOP;
  logicdata[282] = CHANPIN;
  INLINE_NOP;
  logicdata[283] = CHANPIN;
  INLINE_NOP;
  logicdata[284] = CHANPIN;
  INLINE_NOP;
  logicdata[285] = CHANPIN;
  INLINE_NOP;
  logicdata[286] = CHANPIN;
  INLINE_NOP;
  logicdata[287] = CHANPIN;
  INLINE_NOP;
  logicdata[288] = CHANPIN;
  INLINE_NOP;
  logicdata[289] = CHANPIN;
  INLINE_NOP;
  logicdata[290] = CHANPIN;
  INLINE_NOP;
  logicdata[291] = CHANPIN;
  INLINE_NOP;
  logicdata[292] = CHANPIN;
  INLINE_NOP;
  logicdata[293] = CHANPIN;
  INLINE_NOP;
  logicdata[294] = CHANPIN;
  INLINE_NOP;
  logicdata[295] = CHANPIN;
  INLINE_NOP;
  logicdata[296] = CHANPIN;
  INLINE_NOP;
  logicdata[297] = CHANPIN;
  INLINE_NOP;
  logicdata[298] = CHANPIN;
  INLINE_NOP;
  logicdata[299] = CHANPIN;
  INLINE_NOP;
  logicdata[300] = CHANPIN;
  INLINE_NOP;
  logicdata[301] = CHANPIN;
  INLINE_NOP;
  logicdata[302] = CHANPIN;
  INLINE_NOP;
  logicdata[303] = CHANPIN;
  INLINE_NOP;
  logicdata[304] = CHANPIN;
  INLINE_NOP;
  logicdata[305] = CHANPIN;
  INLINE_NOP;
  logicdata[306] = CHANPIN;
  INLINE_NOP;
  logicdata[307] = CHANPIN;
  INLINE_NOP;
  logicdata[308] = CHANPIN;
  INLINE_NOP;
  logicdata[309] = CHANPIN;
  INLINE_NOP;
  logicdata[310] = CHANPIN;
  INLINE_NOP;
  logicdata[311] = CHANPIN;
  INLINE_NOP;
  logicdata[312] = CHANPIN;
  INLINE_NOP;
  logicdata[313] = CHANPIN;
  INLINE_NOP;
  logicdata[314] = CHANPIN;
  INLINE_NOP;
  logicdata[315] = CHANPIN;
  INLINE_NOP;
  logicdata[316] = CHANPIN;
  INLINE_NOP;
  logicdata[317] = CHANPIN;
  INLINE_NOP;
  logicdata[318] = CHANPIN;
  INLINE_NOP;
  logicdata[319] = CHANPIN;
  INLINE_NOP;
  logicdata[320] = CHANPIN;
  INLINE_NOP;
  logicdata[321] = CHANPIN;
  INLINE_NOP;
  logicdata[322] = CHANPIN;
  INLINE_NOP;
  logicdata[323] = CHANPIN;
  INLINE_NOP;
  logicdata[324] = CHANPIN;
  INLINE_NOP;
  logicdata[325] = CHANPIN;
  INLINE_NOP;
  logicdata[326] = CHANPIN;
  INLINE_NOP;
  logicdata[327] = CHANPIN;
  INLINE_NOP;
  logicdata[328] = CHANPIN;
  INLINE_NOP;
  logicdata[329] = CHANPIN;
  INLINE_NOP;
  logicdata[330] = CHANPIN;
  INLINE_NOP;
  logicdata[331] = CHANPIN;
  INLINE_NOP;
  logicdata[332] = CHANPIN;
  INLINE_NOP;
  logicdata[333] = CHANPIN;
  INLINE_NOP;
  logicdata[334] = CHANPIN;
  INLINE_NOP;
  logicdata[335] = CHANPIN;
  INLINE_NOP;
  logicdata[336] = CHANPIN;
  INLINE_NOP;
  logicdata[337] = CHANPIN;
  INLINE_NOP;
  logicdata[338] = CHANPIN;
  INLINE_NOP;
  logicdata[339] = CHANPIN;
  INLINE_NOP;
  logicdata[340] = CHANPIN;
  INLINE_NOP;
  logicdata[341] = CHANPIN;
  INLINE_NOP;
  logicdata[342] = CHANPIN;
  INLINE_NOP;
  logicdata[343] = CHANPIN;
  INLINE_NOP;
  logicdata[344] = CHANPIN;
  INLINE_NOP;
  logicdata[345] = CHANPIN;
  INLINE_NOP;
  logicdata[346] = CHANPIN;
  INLINE_NOP;
  logicdata[347] = CHANPIN;
  INLINE_NOP;
  logicdata[348] = CHANPIN;
  INLINE_NOP;
  logicdata[349] = CHANPIN;
  INLINE_NOP;
  logicdata[350] = CHANPIN;
  INLINE_NOP;
  logicdata[351] = CHANPIN;
  INLINE_NOP;
  logicdata[352] = CHANPIN;
  INLINE_NOP;
  logicdata[353] = CHANPIN;
  INLINE_NOP;
  logicdata[354] = CHANPIN;
  INLINE_NOP;
  logicdata[355] = CHANPIN;
  INLINE_NOP;
  logicdata[356] = CHANPIN;
  INLINE_NOP;
  logicdata[357] = CHANPIN;
  INLINE_NOP;
  logicdata[358] = CHANPIN;
  INLINE_NOP;
  logicdata[359] = CHANPIN;
  INLINE_NOP;
  logicdata[360] = CHANPIN;
  INLINE_NOP;
  logicdata[361] = CHANPIN;
  INLINE_NOP;
  logicdata[362] = CHANPIN;
  INLINE_NOP;
  logicdata[363] = CHANPIN;
  INLINE_NOP;
  logicdata[364] = CHANPIN;
  INLINE_NOP;
  logicdata[365] = CHANPIN;
  INLINE_NOP;
  logicdata[366] = CHANPIN;
  INLINE_NOP;
  logicdata[367] = CHANPIN;
  INLINE_NOP;
  logicdata[368] = CHANPIN;
  INLINE_NOP;
  logicdata[369] = CHANPIN;
  INLINE_NOP;
  logicdata[370] = CHANPIN;
  INLINE_NOP;
  logicdata[371] = CHANPIN;
  INLINE_NOP;
  logicdata[372] = CHANPIN;
  INLINE_NOP;
  logicdata[373] = CHANPIN;
  INLINE_NOP;
  logicdata[374] = CHANPIN;
  INLINE_NOP;
  logicdata[375] = CHANPIN;
  INLINE_NOP;
  logicdata[376] = CHANPIN;
  INLINE_NOP;
  logicdata[377] = CHANPIN;
  INLINE_NOP;
  logicdata[378] = CHANPIN;
  INLINE_NOP;
  logicdata[379] = CHANPIN;
  INLINE_NOP;
  logicdata[380] = CHANPIN;
  INLINE_NOP;
  logicdata[381] = CHANPIN;
  INLINE_NOP;
  logicdata[382] = CHANPIN;
  INLINE_NOP;
  logicdata[383] = CHANPIN;
  INLINE_NOP;
  logicdata[384] = CHANPIN;
  INLINE_NOP;
  logicdata[385] = CHANPIN;
  INLINE_NOP;
  logicdata[386] = CHANPIN;
  INLINE_NOP;
  logicdata[387] = CHANPIN;
  INLINE_NOP;
  logicdata[388] = CHANPIN;
  INLINE_NOP;
  logicdata[389] = CHANPIN;
  INLINE_NOP;
  logicdata[390] = CHANPIN;
  INLINE_NOP;
  logicdata[391] = CHANPIN;
  INLINE_NOP;
  logicdata[392] = CHANPIN;
  INLINE_NOP;
  logicdata[393] = CHANPIN;
  INLINE_NOP;
  logicdata[394] = CHANPIN;
  INLINE_NOP;
  logicdata[395] = CHANPIN;
  INLINE_NOP;
  logicdata[396] = CHANPIN;
  INLINE_NOP;
  logicdata[397] = CHANPIN;
  INLINE_NOP;
  logicdata[398] = CHANPIN;
  INLINE_NOP;
  logicdata[399] = CHANPIN;
  INLINE_NOP;
  logicdata[400] = CHANPIN;
  INLINE_NOP;
  logicdata[401] = CHANPIN;
  INLINE_NOP;
  logicdata[402] = CHANPIN;
  INLINE_NOP;
  logicdata[403] = CHANPIN;
  INLINE_NOP;
  logicdata[404] = CHANPIN;
  INLINE_NOP;
  logicdata[405] = CHANPIN;
  INLINE_NOP;
  logicdata[406] = CHANPIN;
  INLINE_NOP;
  logicdata[407] = CHANPIN;
  INLINE_NOP;
  logicdata[408] = CHANPIN;
  INLINE_NOP;
  logicdata[409] = CHANPIN;
  INLINE_NOP;
  logicdata[410] = CHANPIN;
  INLINE_NOP;
  logicdata[411] = CHANPIN;
  INLINE_NOP;
  logicdata[412] = CHANPIN;
  INLINE_NOP;
  logicdata[413] = CHANPIN;
  INLINE_NOP;
  logicdata[414] = CHANPIN;
  INLINE_NOP;
  logicdata[415] = CHANPIN;
  INLINE_NOP;
  logicdata[416] = CHANPIN;
  INLINE_NOP;
  logicdata[417] = CHANPIN;
  INLINE_NOP;
  logicdata[418] = CHANPIN;
  INLINE_NOP;
  logicdata[419] = CHANPIN;
  INLINE_NOP;
  logicdata[420] = CHANPIN;
  INLINE_NOP;
  logicdata[421] = CHANPIN;
  INLINE_NOP;
  logicdata[422] = CHANPIN;
  INLINE_NOP;
  logicdata[423] = CHANPIN;
  INLINE_NOP;
  logicdata[424] = CHANPIN;
  INLINE_NOP;
  logicdata[425] = CHANPIN;
  INLINE_NOP;
  logicdata[426] = CHANPIN;
  INLINE_NOP;
  logicdata[427] = CHANPIN;
  INLINE_NOP;
  logicdata[428] = CHANPIN;
  INLINE_NOP;
  logicdata[429] = CHANPIN;
  INLINE_NOP;
  logicdata[430] = CHANPIN;
  INLINE_NOP;
  logicdata[431] = CHANPIN;
  INLINE_NOP;
  logicdata[432] = CHANPIN;
  INLINE_NOP;
  logicdata[433] = CHANPIN;
  INLINE_NOP;
  logicdata[434] = CHANPIN;
  INLINE_NOP;
  logicdata[435] = CHANPIN;
  INLINE_NOP;
  logicdata[436] = CHANPIN;
  INLINE_NOP;
  logicdata[437] = CHANPIN;
  INLINE_NOP;
  logicdata[438] = CHANPIN;
  INLINE_NOP;
  logicdata[439] = CHANPIN;
  INLINE_NOP;
  logicdata[440] = CHANPIN;
  INLINE_NOP;
  logicdata[441] = CHANPIN;
  INLINE_NOP;
  logicdata[442] = CHANPIN;
  INLINE_NOP;
  logicdata[443] = CHANPIN;
  INLINE_NOP;
  logicdata[444] = CHANPIN;
  INLINE_NOP;
  logicdata[445] = CHANPIN;
  INLINE_NOP;
  logicdata[446] = CHANPIN;
  INLINE_NOP;
  logicdata[447] = CHANPIN;
  INLINE_NOP;
  logicdata[448] = CHANPIN;
  INLINE_NOP;
  logicdata[449] = CHANPIN;
  INLINE_NOP;
  logicdata[450] = CHANPIN;
  INLINE_NOP;
  logicdata[451] = CHANPIN;
  INLINE_NOP;
  logicdata[452] = CHANPIN;
  INLINE_NOP;
  logicdata[453] = CHANPIN;
  INLINE_NOP;
  logicdata[454] = CHANPIN;
  INLINE_NOP;
  logicdata[455] = CHANPIN;
  INLINE_NOP;
  logicdata[456] = CHANPIN;
  INLINE_NOP;
  logicdata[457] = CHANPIN;
  INLINE_NOP;
  logicdata[458] = CHANPIN;
  INLINE_NOP;
  logicdata[459] = CHANPIN;
  INLINE_NOP;
  logicdata[460] = CHANPIN;
  INLINE_NOP;
  logicdata[461] = CHANPIN;
  INLINE_NOP;
  logicdata[462] = CHANPIN;
  INLINE_NOP;
  logicdata[463] = CHANPIN;
  INLINE_NOP;
  logicdata[464] = CHANPIN;
  INLINE_NOP;
  logicdata[465] = CHANPIN;
  INLINE_NOP;
  logicdata[466] = CHANPIN;
  INLINE_NOP;
  logicdata[467] = CHANPIN;
  INLINE_NOP;
  logicdata[468] = CHANPIN;
  INLINE_NOP;
  logicdata[469] = CHANPIN;
  INLINE_NOP;
  logicdata[470] = CHANPIN;
  INLINE_NOP;
  logicdata[471] = CHANPIN;
  INLINE_NOP;
  logicdata[472] = CHANPIN;
  INLINE_NOP;
  logicdata[473] = CHANPIN;
  INLINE_NOP;
  logicdata[474] = CHANPIN;
  INLINE_NOP;
  logicdata[475] = CHANPIN;
  INLINE_NOP;
  logicdata[476] = CHANPIN;
  INLINE_NOP;
  logicdata[477] = CHANPIN;
  INLINE_NOP;
  logicdata[478] = CHANPIN;
  INLINE_NOP;
  logicdata[479] = CHANPIN;
  INLINE_NOP;
  logicdata[480] = CHANPIN;
  INLINE_NOP;
  logicdata[481] = CHANPIN;
  INLINE_NOP;
  logicdata[482] = CHANPIN;
  INLINE_NOP;
  logicdata[483] = CHANPIN;
  INLINE_NOP;
  logicdata[484] = CHANPIN;
  INLINE_NOP;
  logicdata[485] = CHANPIN;
  INLINE_NOP;
  logicdata[486] = CHANPIN;
  INLINE_NOP;
  logicdata[487] = CHANPIN;
  INLINE_NOP;
  logicdata[488] = CHANPIN;
  INLINE_NOP;
  logicdata[489] = CHANPIN;
  INLINE_NOP;
  logicdata[490] = CHANPIN;
  INLINE_NOP;
  logicdata[491] = CHANPIN;
  INLINE_NOP;
  logicdata[492] = CHANPIN;
  INLINE_NOP;
  logicdata[493] = CHANPIN;
  INLINE_NOP;
  logicdata[494] = CHANPIN;
  INLINE_NOP;
  logicdata[495] = CHANPIN;
  INLINE_NOP;
  logicdata[496] = CHANPIN;
  INLINE_NOP;
  logicdata[497] = CHANPIN;
  INLINE_NOP;
  logicdata[498] = CHANPIN;
  INLINE_NOP;
  logicdata[499] = CHANPIN;
  INLINE_NOP;
  logicdata[500] = CHANPIN;
  INLINE_NOP;
  logicdata[501] = CHANPIN;
  INLINE_NOP;
  logicdata[502] = CHANPIN;
  INLINE_NOP;
  logicdata[503] = CHANPIN;
  INLINE_NOP;
  logicdata[504] = CHANPIN;
  INLINE_NOP;
  logicdata[505] = CHANPIN;
  INLINE_NOP;
  logicdata[506] = CHANPIN;
  INLINE_NOP;
  logicdata[507] = CHANPIN;
  INLINE_NOP;
  logicdata[508] = CHANPIN;
  INLINE_NOP;
  logicdata[509] = CHANPIN;
  INLINE_NOP;
  logicdata[510] = CHANPIN;
  INLINE_NOP;
  logicdata[511] = CHANPIN;
  INLINE_NOP;
  logicdata[512] = CHANPIN;
  INLINE_NOP;
  logicdata[513] = CHANPIN;
  INLINE_NOP;
  logicdata[514] = CHANPIN;
  INLINE_NOP;
  logicdata[515] = CHANPIN;
  INLINE_NOP;
  logicdata[516] = CHANPIN;
  INLINE_NOP;
  logicdata[517] = CHANPIN;
  INLINE_NOP;
  logicdata[518] = CHANPIN;
  INLINE_NOP;
  logicdata[519] = CHANPIN;
  INLINE_NOP;
  logicdata[520] = CHANPIN;
  INLINE_NOP;
  logicdata[521] = CHANPIN;
  INLINE_NOP;
  logicdata[522] = CHANPIN;
  INLINE_NOP;
  logicdata[523] = CHANPIN;
  INLINE_NOP;
  logicdata[524] = CHANPIN;
  INLINE_NOP;
  logicdata[525] = CHANPIN;
  INLINE_NOP;
  logicdata[526] = CHANPIN;
  INLINE_NOP;
  logicdata[527] = CHANPIN;
  INLINE_NOP;
  logicdata[528] = CHANPIN;
  INLINE_NOP;
  logicdata[529] = CHANPIN;
  INLINE_NOP;
  logicdata[530] = CHANPIN;
  INLINE_NOP;
  logicdata[531] = CHANPIN;
  INLINE_NOP;
  logicdata[532] = CHANPIN;
  INLINE_NOP;
  logicdata[533] = CHANPIN;
  INLINE_NOP;
  logicdata[534] = CHANPIN;
  INLINE_NOP;
  logicdata[535] = CHANPIN;
  INLINE_NOP;
  logicdata[536] = CHANPIN;
  INLINE_NOP;
  logicdata[537] = CHANPIN;
  INLINE_NOP;
  logicdata[538] = CHANPIN;
  INLINE_NOP;
  logicdata[539] = CHANPIN;
  INLINE_NOP;
  logicdata[540] = CHANPIN;
  INLINE_NOP;
  logicdata[541] = CHANPIN;
  INLINE_NOP;
  logicdata[542] = CHANPIN;
  INLINE_NOP;
  logicdata[543] = CHANPIN;
  INLINE_NOP;
  logicdata[544] = CHANPIN;
  INLINE_NOP;
  logicdata[545] = CHANPIN;
  INLINE_NOP;
  logicdata[546] = CHANPIN;
  INLINE_NOP;
  logicdata[547] = CHANPIN;
  INLINE_NOP;
  logicdata[548] = CHANPIN;
  INLINE_NOP;
  logicdata[549] = CHANPIN;
  INLINE_NOP;
  logicdata[550] = CHANPIN;
  INLINE_NOP;
  logicdata[551] = CHANPIN;
  INLINE_NOP;
  logicdata[552] = CHANPIN;
  INLINE_NOP;
  logicdata[553] = CHANPIN;
  INLINE_NOP;
  logicdata[554] = CHANPIN;
  INLINE_NOP;
  logicdata[555] = CHANPIN;
  INLINE_NOP;
  logicdata[556] = CHANPIN;
  INLINE_NOP;
  logicdata[557] = CHANPIN;
  INLINE_NOP;
  logicdata[558] = CHANPIN;
  INLINE_NOP;
  logicdata[559] = CHANPIN;
  INLINE_NOP;
  logicdata[560] = CHANPIN;
  INLINE_NOP;
  logicdata[561] = CHANPIN;
  INLINE_NOP;
  logicdata[562] = CHANPIN;
  INLINE_NOP;
  logicdata[563] = CHANPIN;
  INLINE_NOP;
  logicdata[564] = CHANPIN;
  INLINE_NOP;
  logicdata[565] = CHANPIN;
  INLINE_NOP;
  logicdata[566] = CHANPIN;
  INLINE_NOP;
  logicdata[567] = CHANPIN;
  INLINE_NOP;
  logicdata[568] = CHANPIN;
  INLINE_NOP;
  logicdata[569] = CHANPIN;
  INLINE_NOP;
  logicdata[570] = CHANPIN;
  INLINE_NOP;
  logicdata[571] = CHANPIN;
  INLINE_NOP;
  logicdata[572] = CHANPIN;
  INLINE_NOP;
  logicdata[573] = CHANPIN;
  INLINE_NOP;
  logicdata[574] = CHANPIN;
  INLINE_NOP;
  logicdata[575] = CHANPIN;
  INLINE_NOP;
  logicdata[576] = CHANPIN;
  INLINE_NOP;
  logicdata[577] = CHANPIN;
  INLINE_NOP;
  logicdata[578] = CHANPIN;
  INLINE_NOP;
  logicdata[579] = CHANPIN;
  INLINE_NOP;
  logicdata[580] = CHANPIN;
  INLINE_NOP;
  logicdata[581] = CHANPIN;
  INLINE_NOP;
  logicdata[582] = CHANPIN;
  INLINE_NOP;
  logicdata[583] = CHANPIN;
  INLINE_NOP;
  logicdata[584] = CHANPIN;
  INLINE_NOP;
  logicdata[585] = CHANPIN;
  INLINE_NOP;
  logicdata[586] = CHANPIN;
  INLINE_NOP;
  logicdata[587] = CHANPIN;
  INLINE_NOP;
  logicdata[588] = CHANPIN;
  INLINE_NOP;
  logicdata[589] = CHANPIN;
  INLINE_NOP;
  logicdata[590] = CHANPIN;
  INLINE_NOP;
  logicdata[591] = CHANPIN;
  INLINE_NOP;
  logicdata[592] = CHANPIN;
  INLINE_NOP;
  logicdata[593] = CHANPIN;
  INLINE_NOP;
  logicdata[594] = CHANPIN;
  INLINE_NOP;
  logicdata[595] = CHANPIN;
  INLINE_NOP;
  logicdata[596] = CHANPIN;
  INLINE_NOP;
  logicdata[597] = CHANPIN;
  INLINE_NOP;
  logicdata[598] = CHANPIN;
  INLINE_NOP;
  logicdata[599] = CHANPIN;
  INLINE_NOP;
  logicdata[600] = CHANPIN;
  INLINE_NOP;
  logicdata[601] = CHANPIN;
  INLINE_NOP;
  logicdata[602] = CHANPIN;
  INLINE_NOP;
  logicdata[603] = CHANPIN;
  INLINE_NOP;
  logicdata[604] = CHANPIN;
  INLINE_NOP;
  logicdata[605] = CHANPIN;
  INLINE_NOP;
  logicdata[606] = CHANPIN;
  INLINE_NOP;
  logicdata[607] = CHANPIN;
  INLINE_NOP;
  logicdata[608] = CHANPIN;
  INLINE_NOP;
  logicdata[609] = CHANPIN;
  INLINE_NOP;
  logicdata[610] = CHANPIN;
  INLINE_NOP;
  logicdata[611] = CHANPIN;
  INLINE_NOP;
  logicdata[612] = CHANPIN;
  INLINE_NOP;
  logicdata[613] = CHANPIN;
  INLINE_NOP;
  logicdata[614] = CHANPIN;
  INLINE_NOP;
  logicdata[615] = CHANPIN;
  INLINE_NOP;
  logicdata[616] = CHANPIN;
  INLINE_NOP;
  logicdata[617] = CHANPIN;
  INLINE_NOP;
  logicdata[618] = CHANPIN;
  INLINE_NOP;
  logicdata[619] = CHANPIN;
  INLINE_NOP;
  logicdata[620] = CHANPIN;
  INLINE_NOP;
  logicdata[621] = CHANPIN;
  INLINE_NOP;
  logicdata[622] = CHANPIN;
  INLINE_NOP;
  logicdata[623] = CHANPIN;
  INLINE_NOP;
  logicdata[624] = CHANPIN;
  INLINE_NOP;
  logicdata[625] = CHANPIN;
  INLINE_NOP;
  logicdata[626] = CHANPIN;
  INLINE_NOP;
  logicdata[627] = CHANPIN;
  INLINE_NOP;
  logicdata[628] = CHANPIN;
  INLINE_NOP;
  logicdata[629] = CHANPIN;
  INLINE_NOP;
  logicdata[630] = CHANPIN;
  INLINE_NOP;
  logicdata[631] = CHANPIN;
  INLINE_NOP;
  logicdata[632] = CHANPIN;
  INLINE_NOP;
  logicdata[633] = CHANPIN;
  INLINE_NOP;
  logicdata[634] = CHANPIN;
  INLINE_NOP;
  logicdata[635] = CHANPIN;
  INLINE_NOP;
  logicdata[636] = CHANPIN;
  INLINE_NOP;
  logicdata[637] = CHANPIN;
  INLINE_NOP;
  logicdata[638] = CHANPIN;
  INLINE_NOP;
  logicdata[639] = CHANPIN;
  INLINE_NOP;
  logicdata[640] = CHANPIN;
  INLINE_NOP;
  logicdata[641] = CHANPIN;
  INLINE_NOP;
  logicdata[642] = CHANPIN;
  INLINE_NOP;
  logicdata[643] = CHANPIN;
  INLINE_NOP;
  logicdata[644] = CHANPIN;
  INLINE_NOP;
  logicdata[645] = CHANPIN;
  INLINE_NOP;
  logicdata[646] = CHANPIN;
  INLINE_NOP;
  logicdata[647] = CHANPIN;
  INLINE_NOP;
  logicdata[648] = CHANPIN;
  INLINE_NOP;
  logicdata[649] = CHANPIN;
  INLINE_NOP;
  logicdata[650] = CHANPIN;
  INLINE_NOP;
  logicdata[651] = CHANPIN;
  INLINE_NOP;
  logicdata[652] = CHANPIN;
  INLINE_NOP;
  logicdata[653] = CHANPIN;
  INLINE_NOP;
  logicdata[654] = CHANPIN;
  INLINE_NOP;
  logicdata[655] = CHANPIN;
  INLINE_NOP;
  logicdata[656] = CHANPIN;
  INLINE_NOP;
  logicdata[657] = CHANPIN;
  INLINE_NOP;
  logicdata[658] = CHANPIN;
  INLINE_NOP;
  logicdata[659] = CHANPIN;
  INLINE_NOP;
  logicdata[660] = CHANPIN;
  INLINE_NOP;
  logicdata[661] = CHANPIN;
  INLINE_NOP;
  logicdata[662] = CHANPIN;
  INLINE_NOP;
  logicdata[663] = CHANPIN;
  INLINE_NOP;
  logicdata[664] = CHANPIN;
  INLINE_NOP;
  logicdata[665] = CHANPIN;
  INLINE_NOP;
  logicdata[666] = CHANPIN;
  INLINE_NOP;
  logicdata[667] = CHANPIN;
  INLINE_NOP;
  logicdata[668] = CHANPIN;
  INLINE_NOP;
  logicdata[669] = CHANPIN;
  INLINE_NOP;
  logicdata[670] = CHANPIN;
  INLINE_NOP;
  logicdata[671] = CHANPIN;
  INLINE_NOP;
  logicdata[672] = CHANPIN;
  INLINE_NOP;
  logicdata[673] = CHANPIN;
  INLINE_NOP;
  logicdata[674] = CHANPIN;
  INLINE_NOP;
  logicdata[675] = CHANPIN;
  INLINE_NOP;
  logicdata[676] = CHANPIN;
  INLINE_NOP;
  logicdata[677] = CHANPIN;
  INLINE_NOP;
  logicdata[678] = CHANPIN;
  INLINE_NOP;
  logicdata[679] = CHANPIN;
  INLINE_NOP;
  logicdata[680] = CHANPIN;
  INLINE_NOP;
  logicdata[681] = CHANPIN;
  INLINE_NOP;
  logicdata[682] = CHANPIN;
  INLINE_NOP;
  logicdata[683] = CHANPIN;
  INLINE_NOP;
  logicdata[684] = CHANPIN;
  INLINE_NOP;
  logicdata[685] = CHANPIN;
  INLINE_NOP;
  logicdata[686] = CHANPIN;
  INLINE_NOP;
  logicdata[687] = CHANPIN;
  INLINE_NOP;
  logicdata[688] = CHANPIN;
  INLINE_NOP;
  logicdata[689] = CHANPIN;
  INLINE_NOP;
  logicdata[690] = CHANPIN;
  INLINE_NOP;
  logicdata[691] = CHANPIN;
  INLINE_NOP;
  logicdata[692] = CHANPIN;
  INLINE_NOP;
  logicdata[693] = CHANPIN;
  INLINE_NOP;
  logicdata[694] = CHANPIN;
  INLINE_NOP;
  logicdata[695] = CHANPIN;
  INLINE_NOP;
  logicdata[696] = CHANPIN;
  INLINE_NOP;
  logicdata[697] = CHANPIN;
  INLINE_NOP;
  logicdata[698] = CHANPIN;
  INLINE_NOP;
  logicdata[699] = CHANPIN;
  INLINE_NOP;
  logicdata[700] = CHANPIN;
  INLINE_NOP;
  logicdata[701] = CHANPIN;
  INLINE_NOP;
  logicdata[702] = CHANPIN;
  INLINE_NOP;
  logicdata[703] = CHANPIN;
  INLINE_NOP;
  logicdata[704] = CHANPIN;
  INLINE_NOP;
  logicdata[705] = CHANPIN;
  INLINE_NOP;
  logicdata[706] = CHANPIN;
  INLINE_NOP;
  logicdata[707] = CHANPIN;
  INLINE_NOP;
  logicdata[708] = CHANPIN;
  INLINE_NOP;
  logicdata[709] = CHANPIN;
  INLINE_NOP;
  logicdata[710] = CHANPIN;
  INLINE_NOP;
  logicdata[711] = CHANPIN;
  INLINE_NOP;
  logicdata[712] = CHANPIN;
  INLINE_NOP;
  logicdata[713] = CHANPIN;
  INLINE_NOP;
  logicdata[714] = CHANPIN;
  INLINE_NOP;
  logicdata[715] = CHANPIN;
  INLINE_NOP;
  logicdata[716] = CHANPIN;
  INLINE_NOP;
  logicdata[717] = CHANPIN;
  INLINE_NOP;
  logicdata[718] = CHANPIN;
  INLINE_NOP;
  logicdata[719] = CHANPIN;
  INLINE_NOP;
  logicdata[720] = CHANPIN;
  INLINE_NOP;
  logicdata[721] = CHANPIN;
  INLINE_NOP;
  logicdata[722] = CHANPIN;
  INLINE_NOP;
  logicdata[723] = CHANPIN;
  INLINE_NOP;
  logicdata[724] = CHANPIN;
  INLINE_NOP;
  logicdata[725] = CHANPIN;
  INLINE_NOP;
  logicdata[726] = CHANPIN;
  INLINE_NOP;
  logicdata[727] = CHANPIN;
  INLINE_NOP;
  logicdata[728] = CHANPIN;
  INLINE_NOP;
  logicdata[729] = CHANPIN;
  INLINE_NOP;
  logicdata[730] = CHANPIN;
  INLINE_NOP;
  logicdata[731] = CHANPIN;
  INLINE_NOP;
  logicdata[732] = CHANPIN;
  INLINE_NOP;
  logicdata[733] = CHANPIN;
  INLINE_NOP;
  logicdata[734] = CHANPIN;
  INLINE_NOP;
  logicdata[735] = CHANPIN;
  INLINE_NOP;
  logicdata[736] = CHANPIN;
  INLINE_NOP;
  logicdata[737] = CHANPIN;
  INLINE_NOP;
  logicdata[738] = CHANPIN;
  INLINE_NOP;
  logicdata[739] = CHANPIN;
  INLINE_NOP;
  logicdata[740] = CHANPIN;
  INLINE_NOP;
  logicdata[741] = CHANPIN;
  INLINE_NOP;
  logicdata[742] = CHANPIN;
  INLINE_NOP;
  logicdata[743] = CHANPIN;
  INLINE_NOP;
  logicdata[744] = CHANPIN;
  INLINE_NOP;
  logicdata[745] = CHANPIN;
  INLINE_NOP;
  logicdata[746] = CHANPIN;
  INLINE_NOP;
  logicdata[747] = CHANPIN;
  INLINE_NOP;
  logicdata[748] = CHANPIN;
  INLINE_NOP;
  logicdata[749] = CHANPIN;
  INLINE_NOP;
  logicdata[750] = CHANPIN;
  INLINE_NOP;
  logicdata[751] = CHANPIN;
  INLINE_NOP;
  logicdata[752] = CHANPIN;
  INLINE_NOP;
  logicdata[753] = CHANPIN;
  INLINE_NOP;
  logicdata[754] = CHANPIN;
  INLINE_NOP;
  logicdata[755] = CHANPIN;
  INLINE_NOP;
  logicdata[756] = CHANPIN;
  INLINE_NOP;
  logicdata[757] = CHANPIN;
  INLINE_NOP;
  logicdata[758] = CHANPIN;
  INLINE_NOP;
  logicdata[759] = CHANPIN;
  INLINE_NOP;
  logicdata[760] = CHANPIN;
  INLINE_NOP;
  logicdata[761] = CHANPIN;
  INLINE_NOP;
  logicdata[762] = CHANPIN;
  INLINE_NOP;
  logicdata[763] = CHANPIN;
  INLINE_NOP;
  logicdata[764] = CHANPIN;
  INLINE_NOP;
  logicdata[765] = CHANPIN;
  INLINE_NOP;
  logicdata[766] = CHANPIN;
  INLINE_NOP;
  logicdata[767] = CHANPIN;
  INLINE_NOP;
  logicdata[768] = CHANPIN;
  INLINE_NOP;
  logicdata[769] = CHANPIN;
  INLINE_NOP;
  logicdata[770] = CHANPIN;
  INLINE_NOP;
  logicdata[771] = CHANPIN;
  INLINE_NOP;
  logicdata[772] = CHANPIN;
  INLINE_NOP;
  logicdata[773] = CHANPIN;
  INLINE_NOP;
  logicdata[774] = CHANPIN;
  INLINE_NOP;
  logicdata[775] = CHANPIN;
  INLINE_NOP;
  logicdata[776] = CHANPIN;
  INLINE_NOP;
  logicdata[777] = CHANPIN;
  INLINE_NOP;
  logicdata[778] = CHANPIN;
  INLINE_NOP;
  logicdata[779] = CHANPIN;
  INLINE_NOP;
  logicdata[780] = CHANPIN;
  INLINE_NOP;
  logicdata[781] = CHANPIN;
  INLINE_NOP;
  logicdata[782] = CHANPIN;
  INLINE_NOP;
  logicdata[783] = CHANPIN;
  INLINE_NOP;
  logicdata[784] = CHANPIN;
  INLINE_NOP;
  logicdata[785] = CHANPIN;
  INLINE_NOP;
  logicdata[786] = CHANPIN;
  INLINE_NOP;
  logicdata[787] = CHANPIN;
  INLINE_NOP;
  logicdata[788] = CHANPIN;
  INLINE_NOP;
  logicdata[789] = CHANPIN;
  INLINE_NOP;
  logicdata[790] = CHANPIN;
  INLINE_NOP;
  logicdata[791] = CHANPIN;
  INLINE_NOP;
  logicdata[792] = CHANPIN;
  INLINE_NOP;
  logicdata[793] = CHANPIN;
  INLINE_NOP;
  logicdata[794] = CHANPIN;
  INLINE_NOP;
  logicdata[795] = CHANPIN;
  INLINE_NOP;
  logicdata[796] = CHANPIN;
  INLINE_NOP;
  logicdata[797] = CHANPIN;
  INLINE_NOP;
  logicdata[798] = CHANPIN;
  INLINE_NOP;
  logicdata[799] = CHANPIN;
  INLINE_NOP;
  logicdata[800] = CHANPIN;
  INLINE_NOP;
  logicdata[801] = CHANPIN;
  INLINE_NOP;
  logicdata[802] = CHANPIN;
  INLINE_NOP;
  logicdata[803] = CHANPIN;
  INLINE_NOP;
  logicdata[804] = CHANPIN;
  INLINE_NOP;
  logicdata[805] = CHANPIN;
  INLINE_NOP;
  logicdata[806] = CHANPIN;
  INLINE_NOP;
  logicdata[807] = CHANPIN;
  INLINE_NOP;
  logicdata[808] = CHANPIN;
  INLINE_NOP;
  logicdata[809] = CHANPIN;
  INLINE_NOP;
  logicdata[810] = CHANPIN;
  INLINE_NOP;
  logicdata[811] = CHANPIN;
  INLINE_NOP;
  logicdata[812] = CHANPIN;
  INLINE_NOP;
  logicdata[813] = CHANPIN;
  INLINE_NOP;
  logicdata[814] = CHANPIN;
  INLINE_NOP;
  logicdata[815] = CHANPIN;
  INLINE_NOP;
  logicdata[816] = CHANPIN;
  INLINE_NOP;
  logicdata[817] = CHANPIN;
  INLINE_NOP;
  logicdata[818] = CHANPIN;
  INLINE_NOP;
  logicdata[819] = CHANPIN;
  INLINE_NOP;
  logicdata[820] = CHANPIN;
  INLINE_NOP;
  logicdata[821] = CHANPIN;
  INLINE_NOP;
  logicdata[822] = CHANPIN;
  INLINE_NOP;
  logicdata[823] = CHANPIN;
  INLINE_NOP;
  logicdata[824] = CHANPIN;
  INLINE_NOP;
  logicdata[825] = CHANPIN;
  INLINE_NOP;
  logicdata[826] = CHANPIN;
  INLINE_NOP;
  logicdata[827] = CHANPIN;
  INLINE_NOP;
  logicdata[828] = CHANPIN;
  INLINE_NOP;
  logicdata[829] = CHANPIN;
  INLINE_NOP;
  logicdata[830] = CHANPIN;
  INLINE_NOP;
  logicdata[831] = CHANPIN;
  INLINE_NOP;
  logicdata[832] = CHANPIN;
  INLINE_NOP;
  logicdata[833] = CHANPIN;
  INLINE_NOP;
  logicdata[834] = CHANPIN;
  INLINE_NOP;
  logicdata[835] = CHANPIN;
  INLINE_NOP;
  logicdata[836] = CHANPIN;
  INLINE_NOP;
  logicdata[837] = CHANPIN;
  INLINE_NOP;
  logicdata[838] = CHANPIN;
  INLINE_NOP;
  logicdata[839] = CHANPIN;
  INLINE_NOP;
  logicdata[840] = CHANPIN;
  INLINE_NOP;
  logicdata[841] = CHANPIN;
  INLINE_NOP;
  logicdata[842] = CHANPIN;
  INLINE_NOP;
  logicdata[843] = CHANPIN;
  INLINE_NOP;
  logicdata[844] = CHANPIN;
  INLINE_NOP;
  logicdata[845] = CHANPIN;
  INLINE_NOP;
  logicdata[846] = CHANPIN;
  INLINE_NOP;
  logicdata[847] = CHANPIN;
  INLINE_NOP;
  logicdata[848] = CHANPIN;
  INLINE_NOP;
  logicdata[849] = CHANPIN;
  INLINE_NOP;
  logicdata[850] = CHANPIN;
  INLINE_NOP;
  logicdata[851] = CHANPIN;
  INLINE_NOP;
  logicdata[852] = CHANPIN;
  INLINE_NOP;
  logicdata[853] = CHANPIN;
  INLINE_NOP;
  logicdata[854] = CHANPIN;
  INLINE_NOP;
  logicdata[855] = CHANPIN;
  INLINE_NOP;
  logicdata[856] = CHANPIN;
  INLINE_NOP;
  logicdata[857] = CHANPIN;
  INLINE_NOP;
  logicdata[858] = CHANPIN;
  INLINE_NOP;
  logicdata[859] = CHANPIN;
  INLINE_NOP;
  logicdata[860] = CHANPIN;
  INLINE_NOP;
  logicdata[861] = CHANPIN;
  INLINE_NOP;
  logicdata[862] = CHANPIN;
  INLINE_NOP;
  logicdata[863] = CHANPIN;
  INLINE_NOP;
  logicdata[864] = CHANPIN;
  INLINE_NOP;
  logicdata[865] = CHANPIN;
  INLINE_NOP;
  logicdata[866] = CHANPIN;
  INLINE_NOP;
  logicdata[867] = CHANPIN;
  INLINE_NOP;
  logicdata[868] = CHANPIN;
  INLINE_NOP;
  logicdata[869] = CHANPIN;
  INLINE_NOP;
  logicdata[870] = CHANPIN;
  INLINE_NOP;
  logicdata[871] = CHANPIN;
  INLINE_NOP;
  logicdata[872] = CHANPIN;
  INLINE_NOP;
  logicdata[873] = CHANPIN;
  INLINE_NOP;
  logicdata[874] = CHANPIN;
  INLINE_NOP;
  logicdata[875] = CHANPIN;
  INLINE_NOP;
  logicdata[876] = CHANPIN;
  INLINE_NOP;
  logicdata[877] = CHANPIN;
  INLINE_NOP;
  logicdata[878] = CHANPIN;
  INLINE_NOP;
  logicdata[879] = CHANPIN;
  INLINE_NOP;
  logicdata[880] = CHANPIN;
  INLINE_NOP;
  logicdata[881] = CHANPIN;
  INLINE_NOP;
  logicdata[882] = CHANPIN;
  INLINE_NOP;
  logicdata[883] = CHANPIN;
  INLINE_NOP;
  logicdata[884] = CHANPIN;
  INLINE_NOP;
  logicdata[885] = CHANPIN;
  INLINE_NOP;
  logicdata[886] = CHANPIN;
  INLINE_NOP;
  logicdata[887] = CHANPIN;
  INLINE_NOP;
  logicdata[888] = CHANPIN;
  INLINE_NOP;
  logicdata[889] = CHANPIN;
  INLINE_NOP;
  logicdata[890] = CHANPIN;
  INLINE_NOP;
  logicdata[891] = CHANPIN;
  INLINE_NOP;
  logicdata[892] = CHANPIN;
  INLINE_NOP;
  logicdata[893] = CHANPIN;
  INLINE_NOP;
  logicdata[894] = CHANPIN;
  INLINE_NOP;
  logicdata[895] = CHANPIN;
  INLINE_NOP;
  logicdata[896] = CHANPIN;
  INLINE_NOP;
  logicdata[897] = CHANPIN;
  INLINE_NOP;
  logicdata[898] = CHANPIN;
  INLINE_NOP;
  logicdata[899] = CHANPIN;
  INLINE_NOP;
  logicdata[900] = CHANPIN;
  INLINE_NOP;
  logicdata[901] = CHANPIN;
  INLINE_NOP;
  logicdata[902] = CHANPIN;
  INLINE_NOP;
  logicdata[903] = CHANPIN;
  INLINE_NOP;
  logicdata[904] = CHANPIN;
  INLINE_NOP;
  logicdata[905] = CHANPIN;
  INLINE_NOP;
  logicdata[906] = CHANPIN;
  INLINE_NOP;
  logicdata[907] = CHANPIN;
  INLINE_NOP;
  logicdata[908] = CHANPIN;
  INLINE_NOP;
  logicdata[909] = CHANPIN;
  INLINE_NOP;
  logicdata[910] = CHANPIN;
  INLINE_NOP;
  logicdata[911] = CHANPIN;
  INLINE_NOP;
  logicdata[912] = CHANPIN;
  INLINE_NOP;
  logicdata[913] = CHANPIN;
  INLINE_NOP;
  logicdata[914] = CHANPIN;
  INLINE_NOP;
  logicdata[915] = CHANPIN;
  INLINE_NOP;
  logicdata[916] = CHANPIN;
  INLINE_NOP;
  logicdata[917] = CHANPIN;
  INLINE_NOP;
  logicdata[918] = CHANPIN;
  INLINE_NOP;
  logicdata[919] = CHANPIN;
  INLINE_NOP;
  logicdata[920] = CHANPIN;
  INLINE_NOP;
  logicdata[921] = CHANPIN;
  INLINE_NOP;
  logicdata[922] = CHANPIN;
  INLINE_NOP;
  logicdata[923] = CHANPIN;
  INLINE_NOP;
  logicdata[924] = CHANPIN;
  INLINE_NOP;
  logicdata[925] = CHANPIN;
  INLINE_NOP;
  logicdata[926] = CHANPIN;
  INLINE_NOP;
  logicdata[927] = CHANPIN;
  INLINE_NOP;
  logicdata[928] = CHANPIN;
  INLINE_NOP;
  logicdata[929] = CHANPIN;
  INLINE_NOP;
  logicdata[930] = CHANPIN;
  INLINE_NOP;
  logicdata[931] = CHANPIN;
  INLINE_NOP;
  logicdata[932] = CHANPIN;
  INLINE_NOP;
  logicdata[933] = CHANPIN;
  INLINE_NOP;
  logicdata[934] = CHANPIN;
  INLINE_NOP;
  logicdata[935] = CHANPIN;
  INLINE_NOP;
  logicdata[936] = CHANPIN;
  INLINE_NOP;
  logicdata[937] = CHANPIN;
  INLINE_NOP;
  logicdata[938] = CHANPIN;
  INLINE_NOP;
  logicdata[939] = CHANPIN;
  INLINE_NOP;
  logicdata[940] = CHANPIN;
  INLINE_NOP;
  logicdata[941] = CHANPIN;
  INLINE_NOP;
  logicdata[942] = CHANPIN;
  INLINE_NOP;
  logicdata[943] = CHANPIN;
  INLINE_NOP;
  logicdata[944] = CHANPIN;
  INLINE_NOP;
  logicdata[945] = CHANPIN;
  INLINE_NOP;
  logicdata[946] = CHANPIN;
  INLINE_NOP;
  logicdata[947] = CHANPIN;
  INLINE_NOP;
  logicdata[948] = CHANPIN;
  INLINE_NOP;
  logicdata[949] = CHANPIN;
  INLINE_NOP;
  logicdata[950] = CHANPIN;
  INLINE_NOP;
  logicdata[951] = CHANPIN;
  INLINE_NOP;
  logicdata[952] = CHANPIN;
  INLINE_NOP;
  logicdata[953] = CHANPIN;
  INLINE_NOP;
  logicdata[954] = CHANPIN;
  INLINE_NOP;
  logicdata[955] = CHANPIN;
  INLINE_NOP;
  logicdata[956] = CHANPIN;
  INLINE_NOP;
  logicdata[957] = CHANPIN;
  INLINE_NOP;
  logicdata[958] = CHANPIN;
  INLINE_NOP;
  logicdata[959] = CHANPIN;
  INLINE_NOP;
  logicdata[960] = CHANPIN;
  INLINE_NOP;
  logicdata[961] = CHANPIN;
  INLINE_NOP;
  logicdata[962] = CHANPIN;
  INLINE_NOP;
  logicdata[963] = CHANPIN;
  INLINE_NOP;
  logicdata[964] = CHANPIN;
  INLINE_NOP;
  logicdata[965] = CHANPIN;
  INLINE_NOP;
  logicdata[966] = CHANPIN;
  INLINE_NOP;
  logicdata[967] = CHANPIN;
  INLINE_NOP;
  logicdata[968] = CHANPIN;
  INLINE_NOP;
  logicdata[969] = CHANPIN;
  INLINE_NOP;
  logicdata[970] = CHANPIN;
  INLINE_NOP;
  logicdata[971] = CHANPIN;
  INLINE_NOP;
  logicdata[972] = CHANPIN;
  INLINE_NOP;
  logicdata[973] = CHANPIN;
  INLINE_NOP;
  logicdata[974] = CHANPIN;
  INLINE_NOP;
  logicdata[975] = CHANPIN;
  INLINE_NOP;
  logicdata[976] = CHANPIN;
  INLINE_NOP;
  logicdata[977] = CHANPIN;
  INLINE_NOP;
  logicdata[978] = CHANPIN;
  INLINE_NOP;
  logicdata[979] = CHANPIN;
  INLINE_NOP;
  logicdata[980] = CHANPIN;
  INLINE_NOP;
  logicdata[981] = CHANPIN;
  INLINE_NOP;
  logicdata[982] = CHANPIN;
  INLINE_NOP;
  logicdata[983] = CHANPIN;
  INLINE_NOP;
  logicdata[984] = CHANPIN;
  INLINE_NOP;
  logicdata[985] = CHANPIN;
  INLINE_NOP;
  logicdata[986] = CHANPIN;
  INLINE_NOP;
  logicdata[987] = CHANPIN;
  INLINE_NOP;
  logicdata[988] = CHANPIN;
  INLINE_NOP;
  logicdata[989] = CHANPIN;
  INLINE_NOP;
  logicdata[990] = CHANPIN;
  INLINE_NOP;
  logicdata[991] = CHANPIN;
  INLINE_NOP;
  logicdata[992] = CHANPIN;
  INLINE_NOP;
  logicdata[993] = CHANPIN;
  INLINE_NOP;
  logicdata[994] = CHANPIN;
  INLINE_NOP;
  logicdata[995] = CHANPIN;
  INLINE_NOP;
  logicdata[996] = CHANPIN;
  INLINE_NOP;
  logicdata[997] = CHANPIN;
  INLINE_NOP;
  logicdata[998] = CHANPIN;
  INLINE_NOP;
  logicdata[999] = CHANPIN;
  INLINE_NOP;
  logicdata[1000] = CHANPIN;
  INLINE_NOP;
  logicdata[1001] = CHANPIN;
  INLINE_NOP;
  logicdata[1002] = CHANPIN;
  INLINE_NOP;
  logicdata[1003] = CHANPIN;
  INLINE_NOP;
  logicdata[1004] = CHANPIN;
  INLINE_NOP;
  logicdata[1005] = CHANPIN;
  INLINE_NOP;
  logicdata[1006] = CHANPIN;
  INLINE_NOP;
  logicdata[1007] = CHANPIN;
  INLINE_NOP;
  logicdata[1008] = CHANPIN;
  INLINE_NOP;
  logicdata[1009] = CHANPIN;
  INLINE_NOP;
  logicdata[1010] = CHANPIN;
  INLINE_NOP;
  logicdata[1011] = CHANPIN;
  INLINE_NOP;
  logicdata[1012] = CHANPIN;
  INLINE_NOP;
  logicdata[1013] = CHANPIN;
  INLINE_NOP;
  logicdata[1014] = CHANPIN;
  INLINE_NOP;
  logicdata[1015] = CHANPIN;
  INLINE_NOP;
  logicdata[1016] = CHANPIN;
  INLINE_NOP;
  logicdata[1017] = CHANPIN;
  INLINE_NOP;
  logicdata[1018] = CHANPIN;
  INLINE_NOP;
  logicdata[1019] = CHANPIN;
  INLINE_NOP;
  logicdata[1020] = CHANPIN;
  INLINE_NOP;
  logicdata[1021] = CHANPIN;
  INLINE_NOP;
  logicdata[1022] = CHANPIN;
  INLINE_NOP;
  logicdata[1023] = CHANPIN;
  INLINE_NOP;
  logicdata[1024] = CHANPIN;
  INLINE_NOP;
  logicdata[1025] = CHANPIN;
  INLINE_NOP;
  logicdata[1026] = CHANPIN;
  INLINE_NOP;
  logicdata[1027] = CHANPIN;
  INLINE_NOP;
  logicdata[1028] = CHANPIN;
  INLINE_NOP;
  logicdata[1029] = CHANPIN;
  INLINE_NOP;
  logicdata[1030] = CHANPIN;
  INLINE_NOP;
  logicdata[1031] = CHANPIN;
  INLINE_NOP;
  logicdata[1032] = CHANPIN;
  INLINE_NOP;
  logicdata[1033] = CHANPIN;
  INLINE_NOP;
  logicdata[1034] = CHANPIN;
  INLINE_NOP;
  logicdata[1035] = CHANPIN;
  INLINE_NOP;
  logicdata[1036] = CHANPIN;
  INLINE_NOP;
  logicdata[1037] = CHANPIN;
  INLINE_NOP;
  logicdata[1038] = CHANPIN;
  INLINE_NOP;
  logicdata[1039] = CHANPIN;
  INLINE_NOP;
  logicdata[1040] = CHANPIN;
  INLINE_NOP;
  logicdata[1041] = CHANPIN;
  INLINE_NOP;
  logicdata[1042] = CHANPIN;
  INLINE_NOP;
  logicdata[1043] = CHANPIN;
  INLINE_NOP;
  logicdata[1044] = CHANPIN;
  INLINE_NOP;
  logicdata[1045] = CHANPIN;
  INLINE_NOP;
  logicdata[1046] = CHANPIN;
  INLINE_NOP;
  logicdata[1047] = CHANPIN;
  INLINE_NOP;
  logicdata[1048] = CHANPIN;
  INLINE_NOP;
  logicdata[1049] = CHANPIN;
  INLINE_NOP;
  logicdata[1050] = CHANPIN;
  INLINE_NOP;
  logicdata[1051] = CHANPIN;
  INLINE_NOP;
  logicdata[1052] = CHANPIN;
  INLINE_NOP;
  logicdata[1053] = CHANPIN;
  INLINE_NOP;
  logicdata[1054] = CHANPIN;
  INLINE_NOP;
  logicdata[1055] = CHANPIN;
  INLINE_NOP;
  logicdata[1056] = CHANPIN;
  INLINE_NOP;
  logicdata[1057] = CHANPIN;
  INLINE_NOP;
  logicdata[1058] = CHANPIN;
  INLINE_NOP;
  logicdata[1059] = CHANPIN;
  INLINE_NOP;
  logicdata[1060] = CHANPIN;
  INLINE_NOP;
  logicdata[1061] = CHANPIN;
  INLINE_NOP;
  logicdata[1062] = CHANPIN;
  INLINE_NOP;
  logicdata[1063] = CHANPIN;
  INLINE_NOP;
  logicdata[1064] = CHANPIN;
  INLINE_NOP;
  logicdata[1065] = CHANPIN;
  INLINE_NOP;
  logicdata[1066] = CHANPIN;
  INLINE_NOP;
  logicdata[1067] = CHANPIN;
  INLINE_NOP;
  logicdata[1068] = CHANPIN;
  INLINE_NOP;
  logicdata[1069] = CHANPIN;
  INLINE_NOP;
  logicdata[1070] = CHANPIN;
  INLINE_NOP;
  logicdata[1071] = CHANPIN;
  INLINE_NOP;
  logicdata[1072] = CHANPIN;
  INLINE_NOP;
  logicdata[1073] = CHANPIN;
  INLINE_NOP;
  logicdata[1074] = CHANPIN;
  INLINE_NOP;
  logicdata[1075] = CHANPIN;
  INLINE_NOP;
  logicdata[1076] = CHANPIN;
  INLINE_NOP;
  logicdata[1077] = CHANPIN;
  INLINE_NOP;
  logicdata[1078] = CHANPIN;
  INLINE_NOP;
  logicdata[1079] = CHANPIN;
  INLINE_NOP;
  logicdata[1080] = CHANPIN;
  INLINE_NOP;
  logicdata[1081] = CHANPIN;
  INLINE_NOP;
  logicdata[1082] = CHANPIN;
  INLINE_NOP;
  logicdata[1083] = CHANPIN;
  INLINE_NOP;
  logicdata[1084] = CHANPIN;
  INLINE_NOP;
  logicdata[1085] = CHANPIN;
  INLINE_NOP;
  logicdata[1086] = CHANPIN;
  INLINE_NOP;
  logicdata[1087] = CHANPIN;
  INLINE_NOP;
  logicdata[1088] = CHANPIN;
  INLINE_NOP;
  logicdata[1089] = CHANPIN;
  INLINE_NOP;
  logicdata[1090] = CHANPIN;
  INLINE_NOP;
  logicdata[1091] = CHANPIN;
  INLINE_NOP;
  logicdata[1092] = CHANPIN;
  INLINE_NOP;
  logicdata[1093] = CHANPIN;
  INLINE_NOP;
  logicdata[1094] = CHANPIN;
  INLINE_NOP;
  logicdata[1095] = CHANPIN;
  INLINE_NOP;
  logicdata[1096] = CHANPIN;
  INLINE_NOP;
  logicdata[1097] = CHANPIN;
  INLINE_NOP;
  logicdata[1098] = CHANPIN;
  INLINE_NOP;
  logicdata[1099] = CHANPIN;
  INLINE_NOP;
  logicdata[1100] = CHANPIN;
  INLINE_NOP;
  logicdata[1101] = CHANPIN;
  INLINE_NOP;
  logicdata[1102] = CHANPIN;
  INLINE_NOP;
  logicdata[1103] = CHANPIN;
  INLINE_NOP;
  logicdata[1104] = CHANPIN;
  INLINE_NOP;
  logicdata[1105] = CHANPIN;
  INLINE_NOP;
  logicdata[1106] = CHANPIN;
  INLINE_NOP;
  logicdata[1107] = CHANPIN;
  INLINE_NOP;
  logicdata[1108] = CHANPIN;
  INLINE_NOP;
  logicdata[1109] = CHANPIN;
  INLINE_NOP;
  logicdata[1110] = CHANPIN;
  INLINE_NOP;
  logicdata[1111] = CHANPIN;
  INLINE_NOP;
  logicdata[1112] = CHANPIN;
  INLINE_NOP;
  logicdata[1113] = CHANPIN;
  INLINE_NOP;
  logicdata[1114] = CHANPIN;
  INLINE_NOP;
  logicdata[1115] = CHANPIN;
  INLINE_NOP;
  logicdata[1116] = CHANPIN;
  INLINE_NOP;
  logicdata[1117] = CHANPIN;
  INLINE_NOP;
  logicdata[1118] = CHANPIN;
  INLINE_NOP;
  logicdata[1119] = CHANPIN;
  INLINE_NOP;
  logicdata[1120] = CHANPIN;
  INLINE_NOP;
  logicdata[1121] = CHANPIN;
  INLINE_NOP;
  logicdata[1122] = CHANPIN;
  INLINE_NOP;
  logicdata[1123] = CHANPIN;
  INLINE_NOP;
  logicdata[1124] = CHANPIN;
  INLINE_NOP;
  logicdata[1125] = CHANPIN;
  INLINE_NOP;
  logicdata[1126] = CHANPIN;
  INLINE_NOP;
  logicdata[1127] = CHANPIN;
  INLINE_NOP;
  logicdata[1128] = CHANPIN;
  INLINE_NOP;
  logicdata[1129] = CHANPIN;
  INLINE_NOP;
  logicdata[1130] = CHANPIN;
  INLINE_NOP;
  logicdata[1131] = CHANPIN;
  INLINE_NOP;
  logicdata[1132] = CHANPIN;
  INLINE_NOP;
  logicdata[1133] = CHANPIN;
  INLINE_NOP;
  logicdata[1134] = CHANPIN;
  INLINE_NOP;
  logicdata[1135] = CHANPIN;
  INLINE_NOP;
  logicdata[1136] = CHANPIN;
  INLINE_NOP;
  logicdata[1137] = CHANPIN;
  INLINE_NOP;
  logicdata[1138] = CHANPIN;
  INLINE_NOP;
  logicdata[1139] = CHANPIN;
  INLINE_NOP;
  logicdata[1140] = CHANPIN;
  INLINE_NOP;
  logicdata[1141] = CHANPIN;
  INLINE_NOP;
  logicdata[1142] = CHANPIN;
  INLINE_NOP;
  logicdata[1143] = CHANPIN;
  INLINE_NOP;
  logicdata[1144] = CHANPIN;
  INLINE_NOP;
  logicdata[1145] = CHANPIN;
  INLINE_NOP;
  logicdata[1146] = CHANPIN;
  INLINE_NOP;
  logicdata[1147] = CHANPIN;
  INLINE_NOP;
  logicdata[1148] = CHANPIN;
  INLINE_NOP;
  logicdata[1149] = CHANPIN;
  INLINE_NOP;
  logicdata[1150] = CHANPIN;
  INLINE_NOP;
  logicdata[1151] = CHANPIN;
  INLINE_NOP;
  logicdata[1152] = CHANPIN;
  INLINE_NOP;
  logicdata[1153] = CHANPIN;
  INLINE_NOP;
  logicdata[1154] = CHANPIN;
  INLINE_NOP;
  logicdata[1155] = CHANPIN;
  INLINE_NOP;
  logicdata[1156] = CHANPIN;
  INLINE_NOP;
  logicdata[1157] = CHANPIN;
  INLINE_NOP;
  logicdata[1158] = CHANPIN;
  INLINE_NOP;
  logicdata[1159] = CHANPIN;
  INLINE_NOP;
  logicdata[1160] = CHANPIN;
  INLINE_NOP;
  logicdata[1161] = CHANPIN;
  INLINE_NOP;
  logicdata[1162] = CHANPIN;
  INLINE_NOP;
  logicdata[1163] = CHANPIN;
  INLINE_NOP;
  logicdata[1164] = CHANPIN;
  INLINE_NOP;
  logicdata[1165] = CHANPIN;
  INLINE_NOP;
  logicdata[1166] = CHANPIN;
  INLINE_NOP;
  logicdata[1167] = CHANPIN;
  INLINE_NOP;
  logicdata[1168] = CHANPIN;
  INLINE_NOP;
  logicdata[1169] = CHANPIN;
  INLINE_NOP;
  logicdata[1170] = CHANPIN;
  INLINE_NOP;
  logicdata[1171] = CHANPIN;
  INLINE_NOP;
  logicdata[1172] = CHANPIN;
  INLINE_NOP;
  logicdata[1173] = CHANPIN;
  INLINE_NOP;
  logicdata[1174] = CHANPIN;
  INLINE_NOP;
  logicdata[1175] = CHANPIN;
  INLINE_NOP;
  logicdata[1176] = CHANPIN;
  INLINE_NOP;
  logicdata[1177] = CHANPIN;
  INLINE_NOP;
  logicdata[1178] = CHANPIN;
  INLINE_NOP;
  logicdata[1179] = CHANPIN;
  INLINE_NOP;
  logicdata[1180] = CHANPIN;
  INLINE_NOP;
  logicdata[1181] = CHANPIN;
  INLINE_NOP;
  logicdata[1182] = CHANPIN;
  INLINE_NOP;
  logicdata[1183] = CHANPIN;
  INLINE_NOP;
  logicdata[1184] = CHANPIN;
  INLINE_NOP;
  logicdata[1185] = CHANPIN;
  INLINE_NOP;
  logicdata[1186] = CHANPIN;
  INLINE_NOP;
  logicdata[1187] = CHANPIN;
  INLINE_NOP;
  logicdata[1188] = CHANPIN;
  INLINE_NOP;
  logicdata[1189] = CHANPIN;
  INLINE_NOP;
  logicdata[1190] = CHANPIN;
  INLINE_NOP;
  logicdata[1191] = CHANPIN;
  INLINE_NOP;
  logicdata[1192] = CHANPIN;
  INLINE_NOP;
  logicdata[1193] = CHANPIN;
  INLINE_NOP;
  logicdata[1194] = CHANPIN;
  INLINE_NOP;
  logicdata[1195] = CHANPIN;
  INLINE_NOP;
  logicdata[1196] = CHANPIN;
  INLINE_NOP;
  logicdata[1197] = CHANPIN;
  INLINE_NOP;
  logicdata[1198] = CHANPIN;
  INLINE_NOP;
  logicdata[1199] = CHANPIN;
  INLINE_NOP;
  logicdata[1200] = CHANPIN;
  INLINE_NOP;
  logicdata[1201] = CHANPIN;
  INLINE_NOP;
  logicdata[1202] = CHANPIN;
  INLINE_NOP;
  logicdata[1203] = CHANPIN;
  INLINE_NOP;
  logicdata[1204] = CHANPIN;
  INLINE_NOP;
  logicdata[1205] = CHANPIN;
  INLINE_NOP;
  logicdata[1206] = CHANPIN;
  INLINE_NOP;
  logicdata[1207] = CHANPIN;
  INLINE_NOP;
  logicdata[1208] = CHANPIN;
  INLINE_NOP;
  logicdata[1209] = CHANPIN;
  INLINE_NOP;
  logicdata[1210] = CHANPIN;
  INLINE_NOP;
  logicdata[1211] = CHANPIN;
  INLINE_NOP;
  logicdata[1212] = CHANPIN;
  INLINE_NOP;
  logicdata[1213] = CHANPIN;
  INLINE_NOP;
  logicdata[1214] = CHANPIN;
  INLINE_NOP;
  logicdata[1215] = CHANPIN;
  INLINE_NOP;
  logicdata[1216] = CHANPIN;
  INLINE_NOP;
  logicdata[1217] = CHANPIN;
  INLINE_NOP;
  logicdata[1218] = CHANPIN;
  INLINE_NOP;
  logicdata[1219] = CHANPIN;
  INLINE_NOP;
  logicdata[1220] = CHANPIN;
  INLINE_NOP;
  logicdata[1221] = CHANPIN;
  INLINE_NOP;
  logicdata[1222] = CHANPIN;
  INLINE_NOP;
  logicdata[1223] = CHANPIN;
  INLINE_NOP;
  logicdata[1224] = CHANPIN;
  INLINE_NOP;
  logicdata[1225] = CHANPIN;
  INLINE_NOP;
  logicdata[1226] = CHANPIN;
  INLINE_NOP;
  logicdata[1227] = CHANPIN;
  INLINE_NOP;
  logicdata[1228] = CHANPIN;
  INLINE_NOP;
  logicdata[1229] = CHANPIN;
  INLINE_NOP;
  logicdata[1230] = CHANPIN;
  INLINE_NOP;
  logicdata[1231] = CHANPIN;
  INLINE_NOP;
  logicdata[1232] = CHANPIN;
  INLINE_NOP;
  logicdata[1233] = CHANPIN;
  INLINE_NOP;
  logicdata[1234] = CHANPIN;
  INLINE_NOP;
  logicdata[1235] = CHANPIN;
  INLINE_NOP;
  logicdata[1236] = CHANPIN;
  INLINE_NOP;
  logicdata[1237] = CHANPIN;
  INLINE_NOP;
  logicdata[1238] = CHANPIN;
  INLINE_NOP;
  logicdata[1239] = CHANPIN;
  INLINE_NOP;
  logicdata[1240] = CHANPIN;
  INLINE_NOP;
  logicdata[1241] = CHANPIN;
  INLINE_NOP;
  logicdata[1242] = CHANPIN;
  INLINE_NOP;
  logicdata[1243] = CHANPIN;
  INLINE_NOP;
  logicdata[1244] = CHANPIN;
  INLINE_NOP;
  logicdata[1245] = CHANPIN;
  INLINE_NOP;
  logicdata[1246] = CHANPIN;
  INLINE_NOP;
  logicdata[1247] = CHANPIN;
  INLINE_NOP;
  logicdata[1248] = CHANPIN;
  INLINE_NOP;
  logicdata[1249] = CHANPIN;
  INLINE_NOP;
  logicdata[1250] = CHANPIN;
  INLINE_NOP;
  logicdata[1251] = CHANPIN;
  INLINE_NOP;
  logicdata[1252] = CHANPIN;
  INLINE_NOP;
  logicdata[1253] = CHANPIN;
  INLINE_NOP;
  logicdata[1254] = CHANPIN;
  INLINE_NOP;
  logicdata[1255] = CHANPIN;
  INLINE_NOP;
  logicdata[1256] = CHANPIN;
  INLINE_NOP;
  logicdata[1257] = CHANPIN;
  INLINE_NOP;
  logicdata[1258] = CHANPIN;
  INLINE_NOP;
  logicdata[1259] = CHANPIN;
  INLINE_NOP;
  logicdata[1260] = CHANPIN;
  INLINE_NOP;
  logicdata[1261] = CHANPIN;
  INLINE_NOP;
  logicdata[1262] = CHANPIN;
  INLINE_NOP;
  logicdata[1263] = CHANPIN;
  INLINE_NOP;
  logicdata[1264] = CHANPIN;
  INLINE_NOP;
  logicdata[1265] = CHANPIN;
  INLINE_NOP;
  logicdata[1266] = CHANPIN;
  INLINE_NOP;
  logicdata[1267] = CHANPIN;
  INLINE_NOP;
  logicdata[1268] = CHANPIN;
  INLINE_NOP;
  logicdata[1269] = CHANPIN;
  INLINE_NOP;
  logicdata[1270] = CHANPIN;
  INLINE_NOP;
  logicdata[1271] = CHANPIN;
  INLINE_NOP;
  logicdata[1272] = CHANPIN;
  INLINE_NOP;
  logicdata[1273] = CHANPIN;
  INLINE_NOP;
  logicdata[1274] = CHANPIN;
  INLINE_NOP;
  logicdata[1275] = CHANPIN;
  INLINE_NOP;
  logicdata[1276] = CHANPIN;
  INLINE_NOP;
  logicdata[1277] = CHANPIN;
  INLINE_NOP;
  logicdata[1278] = CHANPIN;
  INLINE_NOP;
  logicdata[1279] = CHANPIN;
  INLINE_NOP;
  logicdata[1280] = CHANPIN;
  INLINE_NOP;
  logicdata[1281] = CHANPIN;
  INLINE_NOP;
  logicdata[1282] = CHANPIN;
  INLINE_NOP;
  logicdata[1283] = CHANPIN;
  INLINE_NOP;
  logicdata[1284] = CHANPIN;
  INLINE_NOP;
  logicdata[1285] = CHANPIN;
  INLINE_NOP;
  logicdata[1286] = CHANPIN;
  INLINE_NOP;
  logicdata[1287] = CHANPIN;
  INLINE_NOP;
  logicdata[1288] = CHANPIN;
  INLINE_NOP;
  logicdata[1289] = CHANPIN;
  INLINE_NOP;
  logicdata[1290] = CHANPIN;
  INLINE_NOP;
  logicdata[1291] = CHANPIN;
  INLINE_NOP;
  logicdata[1292] = CHANPIN;
  INLINE_NOP;
  logicdata[1293] = CHANPIN;
  INLINE_NOP;
  logicdata[1294] = CHANPIN;
  INLINE_NOP;
  logicdata[1295] = CHANPIN;
  INLINE_NOP;
  logicdata[1296] = CHANPIN;
  INLINE_NOP;
  logicdata[1297] = CHANPIN;
  INLINE_NOP;
  logicdata[1298] = CHANPIN;
  INLINE_NOP;
  logicdata[1299] = CHANPIN;
  INLINE_NOP;
  logicdata[1300] = CHANPIN;
  INLINE_NOP;
  logicdata[1301] = CHANPIN;
  INLINE_NOP;
  logicdata[1302] = CHANPIN;
  INLINE_NOP;
  logicdata[1303] = CHANPIN;
  INLINE_NOP;
  logicdata[1304] = CHANPIN;
  INLINE_NOP;
  logicdata[1305] = CHANPIN;
  INLINE_NOP;
  logicdata[1306] = CHANPIN;
  INLINE_NOP;
  logicdata[1307] = CHANPIN;
  INLINE_NOP;
  logicdata[1308] = CHANPIN;
  INLINE_NOP;
  logicdata[1309] = CHANPIN;
  INLINE_NOP;
  logicdata[1310] = CHANPIN;
  INLINE_NOP;
  logicdata[1311] = CHANPIN;
  INLINE_NOP;
  logicdata[1312] = CHANPIN;
  INLINE_NOP;
  logicdata[1313] = CHANPIN;
  INLINE_NOP;
  logicdata[1314] = CHANPIN;
  INLINE_NOP;
  logicdata[1315] = CHANPIN;
  INLINE_NOP;
  logicdata[1316] = CHANPIN;
  INLINE_NOP;
  logicdata[1317] = CHANPIN;
  INLINE_NOP;
  logicdata[1318] = CHANPIN;
  INLINE_NOP;
  logicdata[1319] = CHANPIN;
  INLINE_NOP;
  logicdata[1320] = CHANPIN;
  INLINE_NOP;
  logicdata[1321] = CHANPIN;
  INLINE_NOP;
  logicdata[1322] = CHANPIN;
  INLINE_NOP;
  logicdata[1323] = CHANPIN;
  INLINE_NOP;
  logicdata[1324] = CHANPIN;
  INLINE_NOP;
  logicdata[1325] = CHANPIN;
  INLINE_NOP;
  logicdata[1326] = CHANPIN;
  INLINE_NOP;
  logicdata[1327] = CHANPIN;
  INLINE_NOP;
  logicdata[1328] = CHANPIN;
  INLINE_NOP;
  logicdata[1329] = CHANPIN;
  INLINE_NOP;
  logicdata[1330] = CHANPIN;
  INLINE_NOP;
  logicdata[1331] = CHANPIN;
  INLINE_NOP;
  logicdata[1332] = CHANPIN;
  INLINE_NOP;
  logicdata[1333] = CHANPIN;
  INLINE_NOP;
  logicdata[1334] = CHANPIN;
  INLINE_NOP;
  logicdata[1335] = CHANPIN;
  INLINE_NOP;
  logicdata[1336] = CHANPIN;
  INLINE_NOP;
  logicdata[1337] = CHANPIN;
  INLINE_NOP;
  logicdata[1338] = CHANPIN;
  INLINE_NOP;
  logicdata[1339] = CHANPIN;
  INLINE_NOP;
  logicdata[1340] = CHANPIN;
  INLINE_NOP;
  logicdata[1341] = CHANPIN;
  INLINE_NOP;
  logicdata[1342] = CHANPIN;
  INLINE_NOP;
  logicdata[1343] = CHANPIN;
  INLINE_NOP;
  logicdata[1344] = CHANPIN;
  INLINE_NOP;
  logicdata[1345] = CHANPIN;
  INLINE_NOP;
  logicdata[1346] = CHANPIN;
  INLINE_NOP;
  logicdata[1347] = CHANPIN;
  INLINE_NOP;
  logicdata[1348] = CHANPIN;
  INLINE_NOP;
  logicdata[1349] = CHANPIN;
  INLINE_NOP;
  logicdata[1350] = CHANPIN;
  INLINE_NOP;
  logicdata[1351] = CHANPIN;
  INLINE_NOP;
  logicdata[1352] = CHANPIN;
  INLINE_NOP;
  logicdata[1353] = CHANPIN;
  INLINE_NOP;
  logicdata[1354] = CHANPIN;
  INLINE_NOP;
  logicdata[1355] = CHANPIN;
  INLINE_NOP;
  logicdata[1356] = CHANPIN;
  INLINE_NOP;
  logicdata[1357] = CHANPIN;
  INLINE_NOP;
  logicdata[1358] = CHANPIN;
  INLINE_NOP;
  logicdata[1359] = CHANPIN;
  INLINE_NOP;
  logicdata[1360] = CHANPIN;
  INLINE_NOP;
  logicdata[1361] = CHANPIN;
  INLINE_NOP;
  logicdata[1362] = CHANPIN;
  INLINE_NOP;
  logicdata[1363] = CHANPIN;
  INLINE_NOP;
  logicdata[1364] = CHANPIN;
  INLINE_NOP;
  logicdata[1365] = CHANPIN;
  INLINE_NOP;
  logicdata[1366] = CHANPIN;
  INLINE_NOP;
  logicdata[1367] = CHANPIN;
  INLINE_NOP;
  logicdata[1368] = CHANPIN;
  INLINE_NOP;
  logicdata[1369] = CHANPIN;
  INLINE_NOP;
  logicdata[1370] = CHANPIN;
  INLINE_NOP;
  logicdata[1371] = CHANPIN;
  INLINE_NOP;
  logicdata[1372] = CHANPIN;
  INLINE_NOP;
  logicdata[1373] = CHANPIN;
  INLINE_NOP;
  logicdata[1374] = CHANPIN;
  INLINE_NOP;
  logicdata[1375] = CHANPIN;
  INLINE_NOP;
  logicdata[1376] = CHANPIN;
  INLINE_NOP;
  logicdata[1377] = CHANPIN;
  INLINE_NOP;
  logicdata[1378] = CHANPIN;
  INLINE_NOP;
  logicdata[1379] = CHANPIN;
  INLINE_NOP;
  logicdata[1380] = CHANPIN;
  INLINE_NOP;
  logicdata[1381] = CHANPIN;
  INLINE_NOP;
  logicdata[1382] = CHANPIN;
  INLINE_NOP;
  logicdata[1383] = CHANPIN;
  INLINE_NOP;
  logicdata[1384] = CHANPIN;
  INLINE_NOP;
  logicdata[1385] = CHANPIN;
  INLINE_NOP;
  logicdata[1386] = CHANPIN;
  INLINE_NOP;
  logicdata[1387] = CHANPIN;
  INLINE_NOP;
  logicdata[1388] = CHANPIN;
  INLINE_NOP;
  logicdata[1389] = CHANPIN;
  INLINE_NOP;
  logicdata[1390] = CHANPIN;
  INLINE_NOP;
  logicdata[1391] = CHANPIN;
  INLINE_NOP;
  logicdata[1392] = CHANPIN;
  INLINE_NOP;
  logicdata[1393] = CHANPIN;
  INLINE_NOP;
  logicdata[1394] = CHANPIN;
  INLINE_NOP;
  logicdata[1395] = CHANPIN;
  INLINE_NOP;
  logicdata[1396] = CHANPIN;
  INLINE_NOP;
  logicdata[1397] = CHANPIN;
  INLINE_NOP;
  logicdata[1398] = CHANPIN;
  INLINE_NOP;
  logicdata[1399] = CHANPIN;
  INLINE_NOP;
  logicdata[1400] = CHANPIN;
  INLINE_NOP;
  logicdata[1401] = CHANPIN;
  INLINE_NOP;
  logicdata[1402] = CHANPIN;
  INLINE_NOP;
  logicdata[1403] = CHANPIN;
  INLINE_NOP;
  logicdata[1404] = CHANPIN;
  INLINE_NOP;
  logicdata[1405] = CHANPIN;
  INLINE_NOP;
  logicdata[1406] = CHANPIN;
  INLINE_NOP;
  logicdata[1407] = CHANPIN;
  INLINE_NOP;
  logicdata[1408] = CHANPIN;
  INLINE_NOP;
  logicdata[1409] = CHANPIN;
  INLINE_NOP;
  logicdata[1410] = CHANPIN;
  INLINE_NOP;
  logicdata[1411] = CHANPIN;
  INLINE_NOP;
  logicdata[1412] = CHANPIN;
  INLINE_NOP;
  logicdata[1413] = CHANPIN;
  INLINE_NOP;
  logicdata[1414] = CHANPIN;
  INLINE_NOP;
  logicdata[1415] = CHANPIN;
  INLINE_NOP;
  logicdata[1416] = CHANPIN;
  INLINE_NOP;
  logicdata[1417] = CHANPIN;
  INLINE_NOP;
  logicdata[1418] = CHANPIN;
  INLINE_NOP;
  logicdata[1419] = CHANPIN;
  INLINE_NOP;
  logicdata[1420] = CHANPIN;
  INLINE_NOP;
  logicdata[1421] = CHANPIN;
  INLINE_NOP;
  logicdata[1422] = CHANPIN;
  INLINE_NOP;
  logicdata[1423] = CHANPIN;
  INLINE_NOP;
  logicdata[1424] = CHANPIN;
  INLINE_NOP;
  logicdata[1425] = CHANPIN;
  INLINE_NOP;
  logicdata[1426] = CHANPIN;
  INLINE_NOP;
  logicdata[1427] = CHANPIN;
  INLINE_NOP;
  logicdata[1428] = CHANPIN;
  INLINE_NOP;
  logicdata[1429] = CHANPIN;
  INLINE_NOP;
  logicdata[1430] = CHANPIN;
  INLINE_NOP;
  logicdata[1431] = CHANPIN;
  INLINE_NOP;
  logicdata[1432] = CHANPIN;
  INLINE_NOP;
  logicdata[1433] = CHANPIN;
  INLINE_NOP;
  logicdata[1434] = CHANPIN;
  INLINE_NOP;
  logicdata[1435] = CHANPIN;
  INLINE_NOP;
  logicdata[1436] = CHANPIN;
  INLINE_NOP;
  logicdata[1437] = CHANPIN;
  INLINE_NOP;
  logicdata[1438] = CHANPIN;
  INLINE_NOP;
  logicdata[1439] = CHANPIN;
  INLINE_NOP;
  logicdata[1440] = CHANPIN;
  INLINE_NOP;
  logicdata[1441] = CHANPIN;
  INLINE_NOP;
  logicdata[1442] = CHANPIN;
  INLINE_NOP;
  logicdata[1443] = CHANPIN;
  INLINE_NOP;
  logicdata[1444] = CHANPIN;
  INLINE_NOP;
  logicdata[1445] = CHANPIN;
  INLINE_NOP;
  logicdata[1446] = CHANPIN;
  INLINE_NOP;
  logicdata[1447] = CHANPIN;
  INLINE_NOP;
  logicdata[1448] = CHANPIN;
  INLINE_NOP;
  logicdata[1449] = CHANPIN;
  INLINE_NOP;
  logicdata[1450] = CHANPIN;
  INLINE_NOP;
  logicdata[1451] = CHANPIN;
  INLINE_NOP;
  logicdata[1452] = CHANPIN;
  INLINE_NOP;
  logicdata[1453] = CHANPIN;
  INLINE_NOP;
  logicdata[1454] = CHANPIN;
  INLINE_NOP;
  logicdata[1455] = CHANPIN;
  INLINE_NOP;
  logicdata[1456] = CHANPIN;
  INLINE_NOP;
  logicdata[1457] = CHANPIN;
  INLINE_NOP;
  logicdata[1458] = CHANPIN;
  INLINE_NOP;
  logicdata[1459] = CHANPIN;
  INLINE_NOP;
  logicdata[1460] = CHANPIN;
  INLINE_NOP;
  logicdata[1461] = CHANPIN;
  INLINE_NOP;
  logicdata[1462] = CHANPIN;
  INLINE_NOP;
  logicdata[1463] = CHANPIN;
  INLINE_NOP;
  logicdata[1464] = CHANPIN;
  INLINE_NOP;
  logicdata[1465] = CHANPIN;
  INLINE_NOP;
  logicdata[1466] = CHANPIN;
  INLINE_NOP;
  logicdata[1467] = CHANPIN;
  INLINE_NOP;
  logicdata[1468] = CHANPIN;
  INLINE_NOP;
  logicdata[1469] = CHANPIN;
  INLINE_NOP;
  logicdata[1470] = CHANPIN;
  INLINE_NOP;
  logicdata[1471] = CHANPIN;
  INLINE_NOP;
  logicdata[1472] = CHANPIN;
  INLINE_NOP;
  logicdata[1473] = CHANPIN;
  INLINE_NOP;
  logicdata[1474] = CHANPIN;
  INLINE_NOP;
  logicdata[1475] = CHANPIN;
  INLINE_NOP;
  logicdata[1476] = CHANPIN;
  INLINE_NOP;
  logicdata[1477] = CHANPIN;
  INLINE_NOP;
  logicdata[1478] = CHANPIN;
  INLINE_NOP;
  logicdata[1479] = CHANPIN;
  INLINE_NOP;
  logicdata[1480] = CHANPIN;
  INLINE_NOP;
  logicdata[1481] = CHANPIN;
  INLINE_NOP;
  logicdata[1482] = CHANPIN;
  INLINE_NOP;
  logicdata[1483] = CHANPIN;
  INLINE_NOP;
  logicdata[1484] = CHANPIN;
  INLINE_NOP;
  logicdata[1485] = CHANPIN;
  INLINE_NOP;
  logicdata[1486] = CHANPIN;
  INLINE_NOP;
  logicdata[1487] = CHANPIN;
  INLINE_NOP;
  logicdata[1488] = CHANPIN;
  INLINE_NOP;
  logicdata[1489] = CHANPIN;
  INLINE_NOP;
  logicdata[1490] = CHANPIN;
  INLINE_NOP;
  logicdata[1491] = CHANPIN;
  INLINE_NOP;
  logicdata[1492] = CHANPIN;
  INLINE_NOP;
  logicdata[1493] = CHANPIN;
  INLINE_NOP;
  logicdata[1494] = CHANPIN;
  INLINE_NOP;
  logicdata[1495] = CHANPIN;
  INLINE_NOP;
  logicdata[1496] = CHANPIN;
  INLINE_NOP;
  logicdata[1497] = CHANPIN;
  INLINE_NOP;
  logicdata[1498] = CHANPIN;
  INLINE_NOP;
  logicdata[1499] = CHANPIN;
  INLINE_NOP;
  logicdata[1500] = CHANPIN;
  INLINE_NOP;
  logicdata[1501] = CHANPIN;
  INLINE_NOP;
  logicdata[1502] = CHANPIN;
  INLINE_NOP;
  logicdata[1503] = CHANPIN;
  INLINE_NOP;
  logicdata[1504] = CHANPIN;
  INLINE_NOP;
  logicdata[1505] = CHANPIN;
  INLINE_NOP;
  logicdata[1506] = CHANPIN;
  INLINE_NOP;
  logicdata[1507] = CHANPIN;
  INLINE_NOP;
  logicdata[1508] = CHANPIN;
  INLINE_NOP;
  logicdata[1509] = CHANPIN;
  INLINE_NOP;
  logicdata[1510] = CHANPIN;
  INLINE_NOP;
  logicdata[1511] = CHANPIN;
  INLINE_NOP;
  logicdata[1512] = CHANPIN;
  INLINE_NOP;
  logicdata[1513] = CHANPIN;
  INLINE_NOP;
  logicdata[1514] = CHANPIN;
  INLINE_NOP;
  logicdata[1515] = CHANPIN;
  INLINE_NOP;
  logicdata[1516] = CHANPIN;
  INLINE_NOP;
  logicdata[1517] = CHANPIN;
  INLINE_NOP;
  logicdata[1518] = CHANPIN;
  INLINE_NOP;
  logicdata[1519] = CHANPIN;
  INLINE_NOP;
  logicdata[1520] = CHANPIN;
  INLINE_NOP;
  logicdata[1521] = CHANPIN;
  INLINE_NOP;
  logicdata[1522] = CHANPIN;
  INLINE_NOP;
  logicdata[1523] = CHANPIN;
  INLINE_NOP;
  logicdata[1524] = CHANPIN;
  INLINE_NOP;
  logicdata[1525] = CHANPIN;
  INLINE_NOP;
  logicdata[1526] = CHANPIN;
  INLINE_NOP;
  logicdata[1527] = CHANPIN;
  INLINE_NOP;
  logicdata[1528] = CHANPIN;
  INLINE_NOP;
  logicdata[1529] = CHANPIN;
  INLINE_NOP;
  logicdata[1530] = CHANPIN;
  INLINE_NOP;
  logicdata[1531] = CHANPIN;
  INLINE_NOP;
  logicdata[1532] = CHANPIN;
  INLINE_NOP;
  logicdata[1533] = CHANPIN;
  INLINE_NOP;
  logicdata[1534] = CHANPIN;
  INLINE_NOP;
  logicdata[1535] = CHANPIN;
  INLINE_NOP;
  logicdata[1536] = CHANPIN;
  INLINE_NOP;
  logicdata[1537] = CHANPIN;
  INLINE_NOP;
  logicdata[1538] = CHANPIN;
  INLINE_NOP;
  logicdata[1539] = CHANPIN;
  INLINE_NOP;
  logicdata[1540] = CHANPIN;
  INLINE_NOP;
  logicdata[1541] = CHANPIN;
  INLINE_NOP;
  logicdata[1542] = CHANPIN;
  INLINE_NOP;
  logicdata[1543] = CHANPIN;
  INLINE_NOP;
  logicdata[1544] = CHANPIN;
  INLINE_NOP;
  logicdata[1545] = CHANPIN;
  INLINE_NOP;
  logicdata[1546] = CHANPIN;
  INLINE_NOP;
  logicdata[1547] = CHANPIN;
  INLINE_NOP;
  logicdata[1548] = CHANPIN;
  INLINE_NOP;
  logicdata[1549] = CHANPIN;
  INLINE_NOP;
  logicdata[1550] = CHANPIN;
  INLINE_NOP;
  logicdata[1551] = CHANPIN;
  INLINE_NOP;
  logicdata[1552] = CHANPIN;
  INLINE_NOP;
  logicdata[1553] = CHANPIN;
  INLINE_NOP;
  logicdata[1554] = CHANPIN;
  INLINE_NOP;
  logicdata[1555] = CHANPIN;
  INLINE_NOP;
  logicdata[1556] = CHANPIN;
  INLINE_NOP;
  logicdata[1557] = CHANPIN;
  INLINE_NOP;
  logicdata[1558] = CHANPIN;
  INLINE_NOP;
  logicdata[1559] = CHANPIN;
  INLINE_NOP;
  logicdata[1560] = CHANPIN;
  INLINE_NOP;
  logicdata[1561] = CHANPIN;
  INLINE_NOP;
  logicdata[1562] = CHANPIN;
  INLINE_NOP;
  logicdata[1563] = CHANPIN;
  INLINE_NOP;
  logicdata[1564] = CHANPIN;
  INLINE_NOP;
  logicdata[1565] = CHANPIN;
  INLINE_NOP;
  logicdata[1566] = CHANPIN;
  INLINE_NOP;
  logicdata[1567] = CHANPIN;
  INLINE_NOP;
  logicdata[1568] = CHANPIN;
  INLINE_NOP;
  logicdata[1569] = CHANPIN;
  INLINE_NOP;
  logicdata[1570] = CHANPIN;
  INLINE_NOP;
  logicdata[1571] = CHANPIN;
  INLINE_NOP;
  logicdata[1572] = CHANPIN;
  INLINE_NOP;
  logicdata[1573] = CHANPIN;
  INLINE_NOP;
  logicdata[1574] = CHANPIN;
  INLINE_NOP;
  logicdata[1575] = CHANPIN;
  INLINE_NOP;
  logicdata[1576] = CHANPIN;
  INLINE_NOP;
  logicdata[1577] = CHANPIN;
  INLINE_NOP;
  logicdata[1578] = CHANPIN;
  INLINE_NOP;
  logicdata[1579] = CHANPIN;
  INLINE_NOP;
  logicdata[1580] = CHANPIN;
  INLINE_NOP;
  logicdata[1581] = CHANPIN;
  INLINE_NOP;
  logicdata[1582] = CHANPIN;
  INLINE_NOP;
  logicdata[1583] = CHANPIN;
  INLINE_NOP;
  logicdata[1584] = CHANPIN;
  INLINE_NOP;
  logicdata[1585] = CHANPIN;
  INLINE_NOP;
  logicdata[1586] = CHANPIN;
  INLINE_NOP;
  logicdata[1587] = CHANPIN;
  INLINE_NOP;
  logicdata[1588] = CHANPIN;
  INLINE_NOP;
  logicdata[1589] = CHANPIN;
  INLINE_NOP;
  logicdata[1590] = CHANPIN;
  INLINE_NOP;
  logicdata[1591] = CHANPIN;
  INLINE_NOP;
  logicdata[1592] = CHANPIN;
  INLINE_NOP;
  logicdata[1593] = CHANPIN;
  INLINE_NOP;
  logicdata[1594] = CHANPIN;
  INLINE_NOP;
  logicdata[1595] = CHANPIN;
  INLINE_NOP;
  logicdata[1596] = CHANPIN;
  INLINE_NOP;
  logicdata[1597] = CHANPIN;
  INLINE_NOP;
  logicdata[1598] = CHANPIN;
  INLINE_NOP;
  logicdata[1599] = CHANPIN;
  INLINE_NOP;
  logicdata[1600] = CHANPIN;
  INLINE_NOP;
  logicdata[1601] = CHANPIN;
  INLINE_NOP;
  logicdata[1602] = CHANPIN;
  INLINE_NOP;
  logicdata[1603] = CHANPIN;
  INLINE_NOP;
  logicdata[1604] = CHANPIN;
  INLINE_NOP;
  logicdata[1605] = CHANPIN;
  INLINE_NOP;
  logicdata[1606] = CHANPIN;
  INLINE_NOP;
  logicdata[1607] = CHANPIN;
  INLINE_NOP;
  logicdata[1608] = CHANPIN;
  INLINE_NOP;
  logicdata[1609] = CHANPIN;
  INLINE_NOP;
  logicdata[1610] = CHANPIN;
  INLINE_NOP;
  logicdata[1611] = CHANPIN;
  INLINE_NOP;
  logicdata[1612] = CHANPIN;
  INLINE_NOP;
  logicdata[1613] = CHANPIN;
  INLINE_NOP;
  logicdata[1614] = CHANPIN;
  INLINE_NOP;
  logicdata[1615] = CHANPIN;
  INLINE_NOP;
  logicdata[1616] = CHANPIN;
  INLINE_NOP;
  logicdata[1617] = CHANPIN;
  INLINE_NOP;
  logicdata[1618] = CHANPIN;
  INLINE_NOP;
  logicdata[1619] = CHANPIN;
  INLINE_NOP;
  logicdata[1620] = CHANPIN;
  INLINE_NOP;
  logicdata[1621] = CHANPIN;
  INLINE_NOP;
  logicdata[1622] = CHANPIN;
  INLINE_NOP;
  logicdata[1623] = CHANPIN;
  INLINE_NOP;
  logicdata[1624] = CHANPIN;
  INLINE_NOP;
  logicdata[1625] = CHANPIN;
  INLINE_NOP;
  logicdata[1626] = CHANPIN;
  INLINE_NOP;
  logicdata[1627] = CHANPIN;
  INLINE_NOP;
  logicdata[1628] = CHANPIN;
  INLINE_NOP;
  logicdata[1629] = CHANPIN;
  INLINE_NOP;
  logicdata[1630] = CHANPIN;
  INLINE_NOP;
  logicdata[1631] = CHANPIN;
  INLINE_NOP;
  logicdata[1632] = CHANPIN;
  INLINE_NOP;
  logicdata[1633] = CHANPIN;
  INLINE_NOP;
  logicdata[1634] = CHANPIN;
  INLINE_NOP;
  logicdata[1635] = CHANPIN;
  INLINE_NOP;
  logicdata[1636] = CHANPIN;
  INLINE_NOP;
  logicdata[1637] = CHANPIN;
  INLINE_NOP;
  logicdata[1638] = CHANPIN;
  INLINE_NOP;
  logicdata[1639] = CHANPIN;
  INLINE_NOP;
  logicdata[1640] = CHANPIN;
  INLINE_NOP;
  logicdata[1641] = CHANPIN;
  INLINE_NOP;
  logicdata[1642] = CHANPIN;
  INLINE_NOP;
  logicdata[1643] = CHANPIN;
  INLINE_NOP;
  logicdata[1644] = CHANPIN;
  INLINE_NOP;
  logicdata[1645] = CHANPIN;
  INLINE_NOP;
  logicdata[1646] = CHANPIN;
  INLINE_NOP;
  logicdata[1647] = CHANPIN;
  INLINE_NOP;
  logicdata[1648] = CHANPIN;
  INLINE_NOP;
  logicdata[1649] = CHANPIN;
  INLINE_NOP;
  logicdata[1650] = CHANPIN;
  INLINE_NOP;
  logicdata[1651] = CHANPIN;
  INLINE_NOP;
  logicdata[1652] = CHANPIN;
  INLINE_NOP;
  logicdata[1653] = CHANPIN;
  INLINE_NOP;
  logicdata[1654] = CHANPIN;
  INLINE_NOP;
  logicdata[1655] = CHANPIN;
  INLINE_NOP;
  logicdata[1656] = CHANPIN;
  INLINE_NOP;
  logicdata[1657] = CHANPIN;
  INLINE_NOP;
  logicdata[1658] = CHANPIN;
  INLINE_NOP;
  logicdata[1659] = CHANPIN;
  INLINE_NOP;
  logicdata[1660] = CHANPIN;
  INLINE_NOP;
  logicdata[1661] = CHANPIN;
  INLINE_NOP;
  logicdata[1662] = CHANPIN;
  INLINE_NOP;
  logicdata[1663] = CHANPIN;
  INLINE_NOP;
  logicdata[1664] = CHANPIN;
  INLINE_NOP;
  logicdata[1665] = CHANPIN;
  INLINE_NOP;
  logicdata[1666] = CHANPIN;
  INLINE_NOP;
  logicdata[1667] = CHANPIN;
  INLINE_NOP;
  logicdata[1668] = CHANPIN;
  INLINE_NOP;
  logicdata[1669] = CHANPIN;
  INLINE_NOP;
  logicdata[1670] = CHANPIN;
  INLINE_NOP;
  logicdata[1671] = CHANPIN;
  INLINE_NOP;
  logicdata[1672] = CHANPIN;
  INLINE_NOP;
  logicdata[1673] = CHANPIN;
  INLINE_NOP;
  logicdata[1674] = CHANPIN;
  INLINE_NOP;
  logicdata[1675] = CHANPIN;
  INLINE_NOP;
  logicdata[1676] = CHANPIN;
  INLINE_NOP;
  logicdata[1677] = CHANPIN;
  INLINE_NOP;
  logicdata[1678] = CHANPIN;
  INLINE_NOP;
  logicdata[1679] = CHANPIN;
  INLINE_NOP;
  logicdata[1680] = CHANPIN;
  INLINE_NOP;
  logicdata[1681] = CHANPIN;
  INLINE_NOP;
  logicdata[1682] = CHANPIN;
  INLINE_NOP;
  logicdata[1683] = CHANPIN;
  INLINE_NOP;
  logicdata[1684] = CHANPIN;
  INLINE_NOP;
  logicdata[1685] = CHANPIN;
  INLINE_NOP;
  logicdata[1686] = CHANPIN;
  INLINE_NOP;
  logicdata[1687] = CHANPIN;
  INLINE_NOP;
  logicdata[1688] = CHANPIN;
  INLINE_NOP;
  logicdata[1689] = CHANPIN;
  INLINE_NOP;
  logicdata[1690] = CHANPIN;
  INLINE_NOP;
  logicdata[1691] = CHANPIN;
  INLINE_NOP;
  logicdata[1692] = CHANPIN;
  INLINE_NOP;
  logicdata[1693] = CHANPIN;
  INLINE_NOP;
  logicdata[1694] = CHANPIN;
  INLINE_NOP;
  logicdata[1695] = CHANPIN;
  INLINE_NOP;
  logicdata[1696] = CHANPIN;
  INLINE_NOP;
  logicdata[1697] = CHANPIN;
  INLINE_NOP;
  logicdata[1698] = CHANPIN;
  INLINE_NOP;
  logicdata[1699] = CHANPIN;
  INLINE_NOP;
  logicdata[1700] = CHANPIN;
  INLINE_NOP;
  logicdata[1701] = CHANPIN;
  INLINE_NOP;
  logicdata[1702] = CHANPIN;
  INLINE_NOP;
  logicdata[1703] = CHANPIN;
  INLINE_NOP;
  logicdata[1704] = CHANPIN;
  INLINE_NOP;
  logicdata[1705] = CHANPIN;
  INLINE_NOP;
  logicdata[1706] = CHANPIN;
  INLINE_NOP;
  logicdata[1707] = CHANPIN;
  INLINE_NOP;
  logicdata[1708] = CHANPIN;
  INLINE_NOP;
  logicdata[1709] = CHANPIN;
  INLINE_NOP;
  logicdata[1710] = CHANPIN;
  INLINE_NOP;
  logicdata[1711] = CHANPIN;
  INLINE_NOP;
  logicdata[1712] = CHANPIN;
  INLINE_NOP;
  logicdata[1713] = CHANPIN;
  INLINE_NOP;
  logicdata[1714] = CHANPIN;
  INLINE_NOP;
  logicdata[1715] = CHANPIN;
  INLINE_NOP;
  logicdata[1716] = CHANPIN;
  INLINE_NOP;
  logicdata[1717] = CHANPIN;
  INLINE_NOP;
  logicdata[1718] = CHANPIN;
  INLINE_NOP;
  logicdata[1719] = CHANPIN;
  INLINE_NOP;
  logicdata[1720] = CHANPIN;
  INLINE_NOP;
  logicdata[1721] = CHANPIN;
  INLINE_NOP;
  logicdata[1722] = CHANPIN;
  INLINE_NOP;
  logicdata[1723] = CHANPIN;
  INLINE_NOP;
  logicdata[1724] = CHANPIN;
  INLINE_NOP;
  logicdata[1725] = CHANPIN;
  INLINE_NOP;
  logicdata[1726] = CHANPIN;
  INLINE_NOP;
  logicdata[1727] = CHANPIN;
  INLINE_NOP;
  logicdata[1728] = CHANPIN;
  INLINE_NOP;
  logicdata[1729] = CHANPIN;
  INLINE_NOP;
  logicdata[1730] = CHANPIN;
  INLINE_NOP;
  logicdata[1731] = CHANPIN;
  INLINE_NOP;
  logicdata[1732] = CHANPIN;
  INLINE_NOP;
  logicdata[1733] = CHANPIN;
  INLINE_NOP;
  logicdata[1734] = CHANPIN;
  INLINE_NOP;
  logicdata[1735] = CHANPIN;
  INLINE_NOP;
  logicdata[1736] = CHANPIN;
  INLINE_NOP;
  logicdata[1737] = CHANPIN;
  INLINE_NOP;
  logicdata[1738] = CHANPIN;
  INLINE_NOP;
  logicdata[1739] = CHANPIN;
  INLINE_NOP;
  logicdata[1740] = CHANPIN;
  INLINE_NOP;
  logicdata[1741] = CHANPIN;
  INLINE_NOP;
  logicdata[1742] = CHANPIN;
  INLINE_NOP;
  logicdata[1743] = CHANPIN;
  INLINE_NOP;
  logicdata[1744] = CHANPIN;
  INLINE_NOP;
  logicdata[1745] = CHANPIN;
  INLINE_NOP;
  logicdata[1746] = CHANPIN;
  INLINE_NOP;
  logicdata[1747] = CHANPIN;
  INLINE_NOP;
  logicdata[1748] = CHANPIN;
  INLINE_NOP;
  logicdata[1749] = CHANPIN;
  INLINE_NOP;
  logicdata[1750] = CHANPIN;
  INLINE_NOP;
  logicdata[1751] = CHANPIN;
  INLINE_NOP;
  logicdata[1752] = CHANPIN;
  INLINE_NOP;
  logicdata[1753] = CHANPIN;
  INLINE_NOP;
  logicdata[1754] = CHANPIN;
  INLINE_NOP;
  logicdata[1755] = CHANPIN;
  INLINE_NOP;
  logicdata[1756] = CHANPIN;
  INLINE_NOP;
  logicdata[1757] = CHANPIN;
  INLINE_NOP;
  logicdata[1758] = CHANPIN;
  INLINE_NOP;
  logicdata[1759] = CHANPIN;
  INLINE_NOP;
  logicdata[1760] = CHANPIN;
  INLINE_NOP;
  logicdata[1761] = CHANPIN;
  INLINE_NOP;
  logicdata[1762] = CHANPIN;
  INLINE_NOP;
  logicdata[1763] = CHANPIN;
  INLINE_NOP;
  logicdata[1764] = CHANPIN;
  INLINE_NOP;
  logicdata[1765] = CHANPIN;
  INLINE_NOP;
  logicdata[1766] = CHANPIN;
  INLINE_NOP;
  logicdata[1767] = CHANPIN;
  INLINE_NOP;
  logicdata[1768] = CHANPIN;
  INLINE_NOP;
  logicdata[1769] = CHANPIN;
  INLINE_NOP;
  logicdata[1770] = CHANPIN;
  INLINE_NOP;
  logicdata[1771] = CHANPIN;
  INLINE_NOP;
  logicdata[1772] = CHANPIN;
  INLINE_NOP;
  logicdata[1773] = CHANPIN;
  INLINE_NOP;
  logicdata[1774] = CHANPIN;
  INLINE_NOP;
  logicdata[1775] = CHANPIN;
  INLINE_NOP;
  logicdata[1776] = CHANPIN;
  INLINE_NOP;
  logicdata[1777] = CHANPIN;
  INLINE_NOP;
  logicdata[1778] = CHANPIN;
  INLINE_NOP;
  logicdata[1779] = CHANPIN;
  INLINE_NOP;
  logicdata[1780] = CHANPIN;
  INLINE_NOP;
  logicdata[1781] = CHANPIN;
  INLINE_NOP;
  logicdata[1782] = CHANPIN;
  INLINE_NOP;
  logicdata[1783] = CHANPIN;
  INLINE_NOP;
  logicdata[1784] = CHANPIN;
  INLINE_NOP;
  logicdata[1785] = CHANPIN;
  INLINE_NOP;
  logicdata[1786] = CHANPIN;
  INLINE_NOP;
  logicdata[1787] = CHANPIN;
  INLINE_NOP;
  logicdata[1788] = CHANPIN;
  INLINE_NOP;
  logicdata[1789] = CHANPIN;
  INLINE_NOP;
  logicdata[1790] = CHANPIN;
  INLINE_NOP;
  logicdata[1791] = CHANPIN;
  INLINE_NOP;
  logicdata[1792] = CHANPIN;
  INLINE_NOP;
  logicdata[1793] = CHANPIN;
  INLINE_NOP;
  logicdata[1794] = CHANPIN;
  INLINE_NOP;
  logicdata[1795] = CHANPIN;
  INLINE_NOP;
  logicdata[1796] = CHANPIN;
  INLINE_NOP;
  logicdata[1797] = CHANPIN;
  INLINE_NOP;
  logicdata[1798] = CHANPIN;
  INLINE_NOP;
  logicdata[1799] = CHANPIN;
  INLINE_NOP;
  logicdata[1800] = CHANPIN;
  INLINE_NOP;
  logicdata[1801] = CHANPIN;
  INLINE_NOP;
  logicdata[1802] = CHANPIN;
  INLINE_NOP;
  logicdata[1803] = CHANPIN;
  INLINE_NOP;
  logicdata[1804] = CHANPIN;
  INLINE_NOP;
  logicdata[1805] = CHANPIN;
  INLINE_NOP;
  logicdata[1806] = CHANPIN;
  INLINE_NOP;
  logicdata[1807] = CHANPIN;
  INLINE_NOP;
  logicdata[1808] = CHANPIN;
  INLINE_NOP;
  logicdata[1809] = CHANPIN;
  INLINE_NOP;
  logicdata[1810] = CHANPIN;
  INLINE_NOP;
  logicdata[1811] = CHANPIN;
  INLINE_NOP;
  logicdata[1812] = CHANPIN;
  INLINE_NOP;
  logicdata[1813] = CHANPIN;
  INLINE_NOP;
  logicdata[1814] = CHANPIN;
  INLINE_NOP;
  logicdata[1815] = CHANPIN;
  INLINE_NOP;
  logicdata[1816] = CHANPIN;
  INLINE_NOP;
  logicdata[1817] = CHANPIN;
  INLINE_NOP;
  logicdata[1818] = CHANPIN;
  INLINE_NOP;
  logicdata[1819] = CHANPIN;
  INLINE_NOP;
  logicdata[1820] = CHANPIN;
  INLINE_NOP;
  logicdata[1821] = CHANPIN;
  INLINE_NOP;
  logicdata[1822] = CHANPIN;
  INLINE_NOP;
  logicdata[1823] = CHANPIN;
  INLINE_NOP;
  logicdata[1824] = CHANPIN;
  INLINE_NOP;
  logicdata[1825] = CHANPIN;
  INLINE_NOP;
  logicdata[1826] = CHANPIN;
  INLINE_NOP;
  logicdata[1827] = CHANPIN;
  INLINE_NOP;
  logicdata[1828] = CHANPIN;
  INLINE_NOP;
  logicdata[1829] = CHANPIN;
  INLINE_NOP;
  logicdata[1830] = CHANPIN;
  INLINE_NOP;
  logicdata[1831] = CHANPIN;
  INLINE_NOP;
  logicdata[1832] = CHANPIN;
  INLINE_NOP;
  logicdata[1833] = CHANPIN;
  INLINE_NOP;
  logicdata[1834] = CHANPIN;
  INLINE_NOP;
  logicdata[1835] = CHANPIN;
  INLINE_NOP;
  logicdata[1836] = CHANPIN;
  INLINE_NOP;
  logicdata[1837] = CHANPIN;
  INLINE_NOP;
  logicdata[1838] = CHANPIN;
  INLINE_NOP;
  logicdata[1839] = CHANPIN;
  INLINE_NOP;
  logicdata[1840] = CHANPIN;
  INLINE_NOP;
  logicdata[1841] = CHANPIN;
  INLINE_NOP;
  logicdata[1842] = CHANPIN;
  INLINE_NOP;
  logicdata[1843] = CHANPIN;
  INLINE_NOP;
  logicdata[1844] = CHANPIN;
  INLINE_NOP;
  logicdata[1845] = CHANPIN;
  INLINE_NOP;
  logicdata[1846] = CHANPIN;
  INLINE_NOP;
  logicdata[1847] = CHANPIN;
  INLINE_NOP;
  logicdata[1848] = CHANPIN;
  INLINE_NOP;
  logicdata[1849] = CHANPIN;
  INLINE_NOP;
  logicdata[1850] = CHANPIN;
  INLINE_NOP;
  logicdata[1851] = CHANPIN;
  INLINE_NOP;
  logicdata[1852] = CHANPIN;
  INLINE_NOP;
  logicdata[1853] = CHANPIN;
  INLINE_NOP;
  logicdata[1854] = CHANPIN;
  INLINE_NOP;
  logicdata[1855] = CHANPIN;
  INLINE_NOP;
  logicdata[1856] = CHANPIN;
  INLINE_NOP;
  logicdata[1857] = CHANPIN;
  INLINE_NOP;
  logicdata[1858] = CHANPIN;
  INLINE_NOP;
  logicdata[1859] = CHANPIN;
  INLINE_NOP;
  logicdata[1860] = CHANPIN;
  INLINE_NOP;
  logicdata[1861] = CHANPIN;
  INLINE_NOP;
  logicdata[1862] = CHANPIN;
  INLINE_NOP;
  logicdata[1863] = CHANPIN;
  INLINE_NOP;
  logicdata[1864] = CHANPIN;
  INLINE_NOP;
  logicdata[1865] = CHANPIN;
  INLINE_NOP;
  logicdata[1866] = CHANPIN;
  INLINE_NOP;
  logicdata[1867] = CHANPIN;
  INLINE_NOP;
  logicdata[1868] = CHANPIN;
  INLINE_NOP;
  logicdata[1869] = CHANPIN;
  INLINE_NOP;
  logicdata[1870] = CHANPIN;
  INLINE_NOP;
  logicdata[1871] = CHANPIN;
  INLINE_NOP;
  logicdata[1872] = CHANPIN;
  INLINE_NOP;
  logicdata[1873] = CHANPIN;
  INLINE_NOP;
  logicdata[1874] = CHANPIN;
  INLINE_NOP;
  logicdata[1875] = CHANPIN;
  INLINE_NOP;
  logicdata[1876] = CHANPIN;
  INLINE_NOP;
  logicdata[1877] = CHANPIN;
  INLINE_NOP;
  logicdata[1878] = CHANPIN;
  INLINE_NOP;
  logicdata[1879] = CHANPIN;
  INLINE_NOP;
  logicdata[1880] = CHANPIN;
  INLINE_NOP;
  logicdata[1881] = CHANPIN;
  INLINE_NOP;
  logicdata[1882] = CHANPIN;
  INLINE_NOP;
  logicdata[1883] = CHANPIN;
  INLINE_NOP;
  logicdata[1884] = CHANPIN;
  INLINE_NOP;
  logicdata[1885] = CHANPIN;
  INLINE_NOP;
  logicdata[1886] = CHANPIN;
  INLINE_NOP;
  logicdata[1887] = CHANPIN;
  INLINE_NOP;
  logicdata[1888] = CHANPIN;
  INLINE_NOP;
  logicdata[1889] = CHANPIN;
  INLINE_NOP;
  logicdata[1890] = CHANPIN;
  INLINE_NOP;
  logicdata[1891] = CHANPIN;
  INLINE_NOP;
  logicdata[1892] = CHANPIN;
  INLINE_NOP;
  logicdata[1893] = CHANPIN;
  INLINE_NOP;
  logicdata[1894] = CHANPIN;
  INLINE_NOP;
  logicdata[1895] = CHANPIN;
  INLINE_NOP;
  logicdata[1896] = CHANPIN;
  INLINE_NOP;
  logicdata[1897] = CHANPIN;
  INLINE_NOP;
  logicdata[1898] = CHANPIN;
  INLINE_NOP;
  logicdata[1899] = CHANPIN;
  INLINE_NOP;
  logicdata[1900] = CHANPIN;
  INLINE_NOP;
  logicdata[1901] = CHANPIN;
  INLINE_NOP;
  logicdata[1902] = CHANPIN;
  INLINE_NOP;
  logicdata[1903] = CHANPIN;
  INLINE_NOP;
  logicdata[1904] = CHANPIN;
  INLINE_NOP;
  logicdata[1905] = CHANPIN;
  INLINE_NOP;
  logicdata[1906] = CHANPIN;
  INLINE_NOP;
  logicdata[1907] = CHANPIN;
  INLINE_NOP;
  logicdata[1908] = CHANPIN;
  INLINE_NOP;
  logicdata[1909] = CHANPIN;
  INLINE_NOP;
  logicdata[1910] = CHANPIN;
  INLINE_NOP;
  logicdata[1911] = CHANPIN;
  INLINE_NOP;
  logicdata[1912] = CHANPIN;
  INLINE_NOP;
  logicdata[1913] = CHANPIN;
  INLINE_NOP;
  logicdata[1914] = CHANPIN;
  INLINE_NOP;
  logicdata[1915] = CHANPIN;
  INLINE_NOP;
  logicdata[1916] = CHANPIN;
  INLINE_NOP;
  logicdata[1917] = CHANPIN;
  INLINE_NOP;
  logicdata[1918] = CHANPIN;
  INLINE_NOP;
  logicdata[1919] = CHANPIN;
  INLINE_NOP;
  logicdata[1920] = CHANPIN;
  INLINE_NOP;
  logicdata[1921] = CHANPIN;
  INLINE_NOP;
  logicdata[1922] = CHANPIN;
  INLINE_NOP;
  logicdata[1923] = CHANPIN;
  INLINE_NOP;
  logicdata[1924] = CHANPIN;
  INLINE_NOP;
  logicdata[1925] = CHANPIN;
  INLINE_NOP;
  logicdata[1926] = CHANPIN;
  INLINE_NOP;
  logicdata[1927] = CHANPIN;
  INLINE_NOP;
  logicdata[1928] = CHANPIN;
  INLINE_NOP;
  logicdata[1929] = CHANPIN;
  INLINE_NOP;
  logicdata[1930] = CHANPIN;
  INLINE_NOP;
  logicdata[1931] = CHANPIN;
  INLINE_NOP;
  logicdata[1932] = CHANPIN;
  INLINE_NOP;
  logicdata[1933] = CHANPIN;
  INLINE_NOP;
  logicdata[1934] = CHANPIN;
  INLINE_NOP;
  logicdata[1935] = CHANPIN;
  INLINE_NOP;
  logicdata[1936] = CHANPIN;
  INLINE_NOP;
  logicdata[1937] = CHANPIN;
  INLINE_NOP;
  logicdata[1938] = CHANPIN;
  INLINE_NOP;
  logicdata[1939] = CHANPIN;
  INLINE_NOP;
  logicdata[1940] = CHANPIN;
  INLINE_NOP;
  logicdata[1941] = CHANPIN;
  INLINE_NOP;
  logicdata[1942] = CHANPIN;
  INLINE_NOP;
  logicdata[1943] = CHANPIN;
  INLINE_NOP;
  logicdata[1944] = CHANPIN;
  INLINE_NOP;
  logicdata[1945] = CHANPIN;
  INLINE_NOP;
  logicdata[1946] = CHANPIN;
  INLINE_NOP;
  logicdata[1947] = CHANPIN;
  INLINE_NOP;
  logicdata[1948] = CHANPIN;
  INLINE_NOP;
  logicdata[1949] = CHANPIN;
  INLINE_NOP;
  logicdata[1950] = CHANPIN;
  INLINE_NOP;
  logicdata[1951] = CHANPIN;
  INLINE_NOP;
  logicdata[1952] = CHANPIN;
  INLINE_NOP;
  logicdata[1953] = CHANPIN;
  INLINE_NOP;
  logicdata[1954] = CHANPIN;
  INLINE_NOP;
  logicdata[1955] = CHANPIN;
  INLINE_NOP;
  logicdata[1956] = CHANPIN;
  INLINE_NOP;
  logicdata[1957] = CHANPIN;
  INLINE_NOP;
  logicdata[1958] = CHANPIN;
  INLINE_NOP;
  logicdata[1959] = CHANPIN;
  INLINE_NOP;
  logicdata[1960] = CHANPIN;
  INLINE_NOP;
  logicdata[1961] = CHANPIN;
  INLINE_NOP;
  logicdata[1962] = CHANPIN;
  INLINE_NOP;
  logicdata[1963] = CHANPIN;
  INLINE_NOP;
  logicdata[1964] = CHANPIN;
  INLINE_NOP;
  logicdata[1965] = CHANPIN;
  INLINE_NOP;
  logicdata[1966] = CHANPIN;
  INLINE_NOP;
  logicdata[1967] = CHANPIN;
  INLINE_NOP;
  logicdata[1968] = CHANPIN;
  INLINE_NOP;
  logicdata[1969] = CHANPIN;
  INLINE_NOP;
  logicdata[1970] = CHANPIN;
  INLINE_NOP;
  logicdata[1971] = CHANPIN;
  INLINE_NOP;
  logicdata[1972] = CHANPIN;
  INLINE_NOP;
  logicdata[1973] = CHANPIN;
  INLINE_NOP;
  logicdata[1974] = CHANPIN;
  INLINE_NOP;
  logicdata[1975] = CHANPIN;
  INLINE_NOP;
  logicdata[1976] = CHANPIN;
  INLINE_NOP;
  logicdata[1977] = CHANPIN;
  INLINE_NOP;
  logicdata[1978] = CHANPIN;
  INLINE_NOP;
  logicdata[1979] = CHANPIN;
  INLINE_NOP;
  logicdata[1980] = CHANPIN;
  INLINE_NOP;
  logicdata[1981] = CHANPIN;
  INLINE_NOP;
  logicdata[1982] = CHANPIN;
  INLINE_NOP;
  logicdata[1983] = CHANPIN;
  INLINE_NOP;
  logicdata[1984] = CHANPIN;
  INLINE_NOP;
  logicdata[1985] = CHANPIN;
  INLINE_NOP;
  logicdata[1986] = CHANPIN;
  INLINE_NOP;
  logicdata[1987] = CHANPIN;
  INLINE_NOP;
  logicdata[1988] = CHANPIN;
  INLINE_NOP;
  logicdata[1989] = CHANPIN;
  INLINE_NOP;
  logicdata[1990] = CHANPIN;
  INLINE_NOP;
  logicdata[1991] = CHANPIN;
  INLINE_NOP;
  logicdata[1992] = CHANPIN;
  INLINE_NOP;
  logicdata[1993] = CHANPIN;
  INLINE_NOP;
  logicdata[1994] = CHANPIN;
  INLINE_NOP;
  logicdata[1995] = CHANPIN;
  INLINE_NOP;
  logicdata[1996] = CHANPIN;
  INLINE_NOP;
  logicdata[1997] = CHANPIN;
  INLINE_NOP;
  logicdata[1998] = CHANPIN;
  INLINE_NOP;
  logicdata[1999] = CHANPIN;
  INLINE_NOP;
  logicdata[2000] = CHANPIN;
  INLINE_NOP;
  logicdata[2001] = CHANPIN;
  INLINE_NOP;
  logicdata[2002] = CHANPIN;
  INLINE_NOP;
  logicdata[2003] = CHANPIN;
  INLINE_NOP;
  logicdata[2004] = CHANPIN;
  INLINE_NOP;
  logicdata[2005] = CHANPIN;
  INLINE_NOP;
  logicdata[2006] = CHANPIN;
  INLINE_NOP;
  logicdata[2007] = CHANPIN;
  INLINE_NOP;
  logicdata[2008] = CHANPIN;
  INLINE_NOP;
  logicdata[2009] = CHANPIN;
  INLINE_NOP;
  logicdata[2010] = CHANPIN;
  INLINE_NOP;
  logicdata[2011] = CHANPIN;
  INLINE_NOP;
  logicdata[2012] = CHANPIN;
  INLINE_NOP;
  logicdata[2013] = CHANPIN;
  INLINE_NOP;
  logicdata[2014] = CHANPIN;
  INLINE_NOP;
  logicdata[2015] = CHANPIN;
  INLINE_NOP;
  logicdata[2016] = CHANPIN;
  INLINE_NOP;
  logicdata[2017] = CHANPIN;
  INLINE_NOP;
  logicdata[2018] = CHANPIN;
  INLINE_NOP;
  logicdata[2019] = CHANPIN;
  INLINE_NOP;
  logicdata[2020] = CHANPIN;
  INLINE_NOP;
  logicdata[2021] = CHANPIN;
  INLINE_NOP;
  logicdata[2022] = CHANPIN;
  INLINE_NOP;
  logicdata[2023] = CHANPIN;
  INLINE_NOP;
  logicdata[2024] = CHANPIN;
  INLINE_NOP;
  logicdata[2025] = CHANPIN;
  INLINE_NOP;
  logicdata[2026] = CHANPIN;
  INLINE_NOP;
  logicdata[2027] = CHANPIN;
  INLINE_NOP;
  logicdata[2028] = CHANPIN;
  INLINE_NOP;
  logicdata[2029] = CHANPIN;
  INLINE_NOP;
  logicdata[2030] = CHANPIN;
  INLINE_NOP;
  logicdata[2031] = CHANPIN;
  INLINE_NOP;
  logicdata[2032] = CHANPIN;
  INLINE_NOP;
  logicdata[2033] = CHANPIN;
  INLINE_NOP;
  logicdata[2034] = CHANPIN;
  INLINE_NOP;
  logicdata[2035] = CHANPIN;
  INLINE_NOP;
  logicdata[2036] = CHANPIN;
  INLINE_NOP;
  logicdata[2037] = CHANPIN;
  INLINE_NOP;
  logicdata[2038] = CHANPIN;
  INLINE_NOP;
  logicdata[2039] = CHANPIN;
  INLINE_NOP;
  logicdata[2040] = CHANPIN;
  INLINE_NOP;
  logicdata[2041] = CHANPIN;
  INLINE_NOP;
  logicdata[2042] = CHANPIN;
  INLINE_NOP;
  logicdata[2043] = CHANPIN;
  INLINE_NOP;
  logicdata[2044] = CHANPIN;
  INLINE_NOP;
  logicdata[2045] = CHANPIN;
  INLINE_NOP;
  logicdata[2046] = CHANPIN;
  INLINE_NOP;
  logicdata[2047] = CHANPIN;

  DEBUG_OFF; /* debug timing measurement */

  /* re-enable interrupts now that we're done sampling. */
  //sei();

  /*
   * dump the samples back to the SUMP client.  nothing special
   * is done for any triggers, this is effectively the 0/100 buffer split.
   */
  for (i = 0 ; i < 2048; i++) {
    Serial.write(logicdata[i]);
  }
}





